### ISSUE TITLE
 File "/faucet-src/faucet/valve.py", line 946, in _get_eth_srcs_learned_on_port	    for eth_src, host_cache_entry in list(vlan.host_cache.items()):	AttributeError: 'int' object has no attribute 'host_cache'	

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#1037]
faucet_mininet_test_unit.FaucetUntaggedMirrorTest.test_untagged	ERROR	_StringException: Traceback (most recent call last):	  File "/faucet-src/tests/faucet_mininet_test_base.py", line 260, in tearDown	    self.verify_no_exception(self.env['faucet']['FAUCET_EXCEPTION_LOG'])	  File "/faucet-src/tests/faucet_mininet_test_base.py", line 495, in verify_no_exception	    exception_log_name, exception_contents))	  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual	    assertion_func(first, second, msg=msg)	  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual	    raise self.failureException(msg)	AssertionError: /tmp/faucet-tests-l1A1Pu/FaucetUntaggedMirrorTest-test_untagged/faucet-exception.log log contains Sep 30 02:55:43 faucet.exception ERROR    Unhandled exception, killing RYU	Traceback (most recent call last):	  File "/faucet-src/faucet/valve_util.py", line 34, in __koe	    func(*args, **kwargs)	  File "/faucet-src/faucet/faucet.py", line 500, in port_status_handler	    dp_id, port_no, reason, port_status)	  File "/faucet-src/faucet/valve.py", line 328, in port_status_handler	    ofmsgs.extend(self.port_delete(dp_id, port_no))	  File "/faucet-src/faucet/valve.py", line 594, in port_delete	    return self.ports_delete(dp_id, [port_num])	  File "/faucet-src/faucet/valve.py", line 580, in ports_delete	    self._get_eth_srcs_learned_on_port(self.dp, port.number)))	  File "/faucet-src/faucet/valve.py", line 946, in _get_eth_srcs_learned_on_port	    for eth_src, host_cache_entry in list(vlan.host_cache.items()):	AttributeError: 'int' object has no attribute 'host_cache'

**Comment by anarkiwi** [comment]
vlans:
    100:
        description: "untagged"
        unicast_flood: False

dps:
    faucet-1:
        ofchannel_log: /tmp/faucet-tests-l1A1Pu/FaucetUntaggedMirrorTest-test_untagged/ofchannel.log
        dp_id: 0x1606b1bb
        hardware: "Open vSwitch"


        interfaces:
            1:
                native_vlan: 100
                description: "b1"
            2:
                native_vlan: 100
                description: "b2"
            3:
                native_vlan: 100
                description: "b3"
                mirror: 1
            4:
                native_vlan: 100
                description: "b4"

root@faucet:~# more /tmp/faucet-tests-l1A1Pu/FaucetUntaggedMirrorTest-test_untagged/faucet.log 
Sep 30 02:55:42 faucet INFO     Add new datapath DPID 369537467 (0x1606b1bb)
Sep 30 02:55:43 faucet DEBUG    DPID 369537467 (0x1606b1bb) connected
Sep 30 02:55:43 faucet.valve INFO     DPID 369537467 (0x1606b1bb) Cold start configuring DP
Sep 30 02:55:43 faucet.valve INFO     DPID 369537467 (0x1606b1bb) Configuring VLAN 100 vid:100 ports:Port 1,Port 2,Port 4
Sep 30 02:55:43 faucet.valve INFO     DPID 369537467 (0x1606b1bb) Sending config for Port 1
Sep 30 02:55:43 faucet.valve INFO     DPID 369537467 (0x1606b1bb) Sending config for Port 2
Sep 30 02:55:43 faucet.valve INFO     DPID 369537467 (0x1606b1bb) Sending config for Port 4
Sep 30 02:55:43 faucet.valve DEBUG    DPID 369537467 (0x1606b1bb) Packet_in src:9a:9e:4c:43:2b:f3 in_port:2 vid:100
Sep 30 02:55:43 faucet.valve INFO     DPID 369537467 (0x1606b1bb) learned 9a:9e:4c:43:2b:f3 on Port 2 on VLAN 100 (1 hosts total)
Sep 30 02:55:43 faucet.valve INFO     DPID 369537467 (0x1606b1bb) Port 3 down
Sep 30 02:55:43 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/faucet-src/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/faucet-src/faucet/faucet.py", line 500, in port_status_handler
    dp_id, port_no, reason, port_status)
  File "/faucet-src/faucet/valve.py", line 328, in port_status_handler
    ofmsgs.extend(self.port_delete(dp_id, port_no))
  File "/faucet-src/faucet/valve.py", line 594, in port_delete
    return self.ports_delete(dp_id, [port_num])
  File "/faucet-src/faucet/valve.py", line 580, in ports_delete
    self._get_eth_srcs_learned_on_port(self.dp, port.number)))
  File "/faucet-src/faucet/valve.py", line 946, in _get_eth_srcs_learned_on_port
    for eth_src, host_cache_entry in list(vlan.host_cache.items()):
AttributeError: 'int' object has no attribute 'host_cache'
Sep 30 02:56:49 faucet INFO     Add new datapath DPID 369537467 (0x1606b1bb)
Sep 30 02:56:50 faucet DEBUG    DPID 369537467 (0x1606b1bb) connected

**Comment by anarkiwi** [comment]
We crash if a mirror port changes state due to unresolved VLAN references.

**Comment by anarkiwi** [comment]
https://github.com/anarkiwi/faucet/commit/6725e18a608a8ae14d6492850e24401a5d352b1a
