### ISSUE TITLE
FaucetAPI.get_config() throws error that 'DP' object has no attribute 'config_dict'

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#1155]
When calling:
```
self.faucet_api.get_config()
```
throws:
```
faucet_1      | Traceback (most recent call last):
faucet_1      |   File "/usr/bin/ryu-manager", line 11, in <module>
faucet_1      |     load_entry_point('ryu==4.18', 'console_scripts', 'ryu-manager')()
faucet_1      |   File "/usr/lib/python3.6/site-packages/ryu/cmd/manager.py", line 101, in main
faucet_1      |     services.extend(app_mgr.instantiate_apps(**contexts))
faucet_1      |   File "/usr/lib/python3.6/site-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
faucet_1      |     self._instantiate(app_name, cls, *args, **kwargs)
faucet_1      |   File "/usr/lib/python3.6/site-packages/ryu/base/app_manager.py", line 495, in _instantiate
faucet_1      |     app = cls(*args, **kwargs)
faucet_1      |   File "/usr/lib/python3.6/site-packages/faucet/example_app.py", line 22, in __init__
faucet_1      |     self._api_registered() 
faucet_1      |   File "/usr/lib/python3.6/site-packages/faucet/example_app.py", line 27, in _api_registered
faucet_1      |     self.print_faucet_config()
faucet_1      |   File "/usr/lib/python3.6/site-packages/faucet/example_app.py", line 33, in print_faucet_config
faucet_1      |     f.write(self.faucet_api.get_config())
faucet_1      |   File "/usr/lib/python3.6/site-packages/faucet/faucet_api.py", line 69, in get_config
faucet_1      |     return self.faucet.get_config()
faucet_1      |   File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 319, in get_config
faucet_1      |     return get_config_for_api(self.valves)
faucet_1      |   File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 174, in get_config_for_api
faucet_1      |     valve_conf = valve.get_config_dict()
faucet_1      |   File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 912, in get_config_dict
faucet_1      |     return self.dp.config_dict()
faucet_1      | AttributeError: 'DP' object has no attribute 'config_dict'
```

**Comment by anarkiwi** [comment]
Faucet API is not well specified or tested at this time. At present the
config update mechanism is HUP and FAUCET will update and minimize flow
table diffs where possible.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/pull/1227
