### ISSUE TITLE
Ryu raises TypeError when parsing fragmented ICMPv4 echo to faucet vip

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#1171]
I have Faucet (latest master) configured with an IPv4 vip (10.100.0.254). When I run "h1 ping -s 1476 10.100.0.254", ryu raises an exception.  The echo request is fragmented and there are two packet_in's. The second packet_in containing the fragment appears to cause the exception.

Excerpt from faucet_exception.log:
```
Nov 03 10:07:48 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/Users/bfish/code/faucet/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/Users/bfish/code/faucet/faucet/faucet.py", line 375, in packet_in_handler
    flowmods = valve.rcv_packet(other_valves, pkt_meta)
  File "/Users/bfish/code/faucet/faucet/valve.py", line 744, in rcv_packet
    control_plane_ofmsgs = self.control_plane_handler(pkt_meta)
  File "/Users/bfish/code/faucet/faucet/valve.py", line 613, in control_plane_handler
    pkt_meta.reparse_ip(route_manager.ETH_TYPE)
  File "/Users/bfish/code/faucet/faucet/valve_packet.py", line 499, in reparse_ip
    self.reparse(ip_header_size(eth_type) + payload)
  File "/Users/bfish/code/faucet/faucet/valve_packet.py", line 487, in reparse
    self.data, max_len)
  File "/Users/bfish/code/faucet/faucet/valve_packet.py", line 99, in parse_packet_in_pkt
    pkt = packet.Packet(data)
  File "/Users/bfish/code/faucet/venv36_ryu/lib/python3.6/site-packages/ryu/lib/packet/packet.py", line 67, in __init__
    self._parser(parse_cls)
  File "/Users/bfish/code/faucet/venv36_ryu/lib/python3.6/site-packages/ryu/lib/packet/packet.py", line 79, in _parser
    if proto:
  File "/Users/bfish/code/faucet/venv36_ryu/lib/python3.6/site-packages/ryu/lib/packet/icmp.py", line 122, in __len__
    return self._MIN_LEN + len(self.data)
TypeError: object of type 'NoneType' has no len()
```

Faucet Config:
```
vlans:
    100:
        faucet_vips: ["10.100.0.254/8", "fc00::10:10:10:1/64"]

dps:
    1:
        interfaces:
            1:
                native_vlan: 100
            2:
                native_vlan: 100
```

Catching TypeError and printing out the packet confirms it is the 2nd fragment:

```diff
diff --git a/faucet/valve_packet.py b/faucet/valve_packet.py
index 1dc410f..7b2d463 100644
--- a/faucet/valve_packet.py
+++ b/faucet/valve_packet.py
@@ -108,8 +108,9 @@ def parse_packet_in_pkt(data, max_len):
             if vlan_pkt:
                 vlan_vid = vlan_pkt.vid
                 eth_type = vlan_pkt.ethertype
-    except (AssertionError, stream_parser.StreamParser.TooSmallException):
-        pass
+    except (TypeError, AssertionError, stream_parser.StreamParser.TooSmallException):
+        print("parse_packet_in_pkt(maxlen=%d): %s" % (max_len, data.hex()))
+        #pass
 
     return (pkt, eth_pkt, vlan_vid, eth_type)
 

```

Results in:

```
parse_packet_in_pkt(maxlen=60): 0e00000000010ac2bb0242968100006408004500001803c000b94001610a0a0000010a6400fec0c1c2c3
parse_packet_in_pkt(maxlen=60): 0e00000000010ac2bb0242968100006408004500001803c000b94001610a0a0000010a6400fec0c1c2c3
parse_packet_in_pkt(maxlen=60): 0e00000000010ac2bb0242968100006408004500001803e900b9400160e10a0000010a6400fec0c1c2c3
parse_packet_in_pkt(maxlen=60): 0e00000000010ac2bb0242968100006408004500001803e900b9400160e10a0000010a6400fec0c1c2c3
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/f0b35e7125c7ee243ec4c9e2d87da3e38bddfba4
