### ISSUE TITLE
Multiple dps and IVR unsupported

### ISSUE THREAD

**Issue by KitL** [faucetsdn/faucet#1204]
Configuration parsing fails when using multiple dps with inter-vlan routing even if the second dp does not have any of the IVR vlans on it. Actually it looks like the error in my example is actually caused when IVR does not route between every configured vlan, which should also be fixed.

I recommend that we have to add a router to the configuration of a DP before any routing will be attempted. 

So:

```
dps:
    sw1:
        router: 'router-office-guest'
```

Then dont try to add the router to the dp if it isnt configured.

=======
Example:
=======
Config:
```
vlans:
    office:
        vid: 100
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
    guest:
        vid: 200
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['10.0.200.254/24', '2001:200::1/64', 'fe80::c00:00ff:fe00:2001/64']
    test:
        vid: 300

routers:
    router-office-guest:
        vlans: [office, guest]

dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            1:
                name: "h1"
                native_vlan: office
            3:
                name: "g1"
                native_vlan: guest
    sw2:
        dp_id: 0x2
        hardware: "Allied-Telesis"
        interfaces:
            1:
                name: "pi"
                native_vlan: 300
            2:
                name: "laptop"
                native_vlan: 300
```

Output:
```
Nov 15 03:44:49 faucet.config ERROR    Error in config file: could not resolve VLAN office, [VLAN 300 vid:300 ports:Port 1,Port 2]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 133, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 506, in finalize_config
    resolve_vlan_names_in_routers()
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 487, in resolve_vlan_names_in_routers
    vlan_name, list(self.vlans.values()))
AssertionError: could not resolve VLAN office, [VLAN 300 vid:300 ports:Port 1,Port 2]
Nov 15 03:44:49 faucet ERROR    new config bad - rejecting
```

**Comment by aappachi** [comment]
Can you assign it to me. I can take a look.

**Comment by KitL** [comment]
I am not sure if I can, it seems to only want to let me assign one of the admins. But your welcome to take a look at it.

**Comment by anarkiwi** [comment]
This was fixed in https://github.com/anarkiwi/faucet/commit/e72d1258dc4f5eb472331f56b44428a88960fd65 et al.
