### ISSUE TITLE
Unhandled exception with 0 > vid > 65535

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1211]
Steps to reproduce:
1.
```
include:
    - acls.yaml

vlans:
    office:
        vid: 65536
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
    guest:
        vid: 65536
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['10.0.200.254/24', '2001:200::1/64', 'fe80::c00:00ff:fe00:2001/64']

dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            1:
                name: "h1"
                description: "host1 container"
                native_vlan: office
                acl_in: access-port-protect
    sw2:
        dp_id: 0x2
        hardware: "Allied-Telesis"
        interfaces:
            1:
                name: "pi"
                description: "Raspberry Pi"
                native_vlan: office
                acl_in: access-port-protect
            24:
                name: "trunk"
                description: "VLAN trunk to sw1"
                tagged_vlans: [office, guest]
```
2. Start faucet
3. (Seemingly infinite loop)
```
Nov 16 03:18:42 faucet INFO     Add new datapath DPID 1 (0x1)
Nov 16 03:18:42 faucet INFO     Add new datapath DPID 2 (0x2)
Nov 16 03:18:42 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 307, in advertise
    flowmods = valve.advertise()
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 313, in advertise
    ofmsgs.extend(route_manager.advertise(vlan))
  File "/usr/lib/python3.6/site-packages/faucet/valve_route.py", line 886, in advertise
    other_vips))
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 291, in flood_pkt
    pkt = packet_builder(self, vid, *args)
  File "/usr/lib/python3.6/site-packages/faucet/valve_packet.py", line 460, in router_advert
    pkt.serialize()
  File "/usr/lib/python3.6/site-packages/ryu/lib/packet/packet.py", line 99, in serialize
    data = p.serialize(self.data, prev)
  File "/usr/lib/python3.6/site-packages/ryu/lib/packet/vlan.py", line 55, in serialize
    return struct.pack(vlan._PACK_STR, tci, self.ethertype)
struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by gizmoguy** [comment]
The VID field in a VLAN header is limited to 12 bits:

https://en.wikipedia.org/wiki/IEEE_802.1Q#Frame_format

So the VID-space is actually much smaller than this (0-4095).

**Comment by anarkiwi** [comment]
Restrict VID range.

https://github.com/faucetsdn/faucet/pull/1233
