### ISSUE TITLE
Unhandled Exception with switch interfaces and empty vlan vid

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1236]
Use this config:
```
include:
    - acls.yaml
vlans:
    office:
        vid:
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            5:
                name: "trunk"
                description: "VLAN trunk to sw2"
                tagged_vlans: [office]
                acl_in: access-port-protect
```
Crash:
```
Nov 19 22:53:45 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 342, in advertise
    flowmods = valve.advertise()
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 313, in advertise
    ofmsgs.extend(route_manager.advertise(vlan))
  File "/usr/lib/python3.6/site-packages/faucet/valve_route.py", line 890, in advertise
    other_vips))
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 291, in flood_pkt
    pkt = packet_builder(self, vid, *args)
  File "/usr/lib/python3.6/site-packages/faucet/valve_packet.py", line 460, in router_advert
    pkt.serialize()
  File "/usr/lib/python3.6/site-packages/ryu/lib/packet/packet.py", line 99, in serialize
    data = p.serialize(self.data, prev)
  File "/usr/lib/python3.6/site-packages/ryu/lib/packet/vlan.py", line 54, in serialize
    tci = self.pcp << 13 | self.cfi << 12 | self.vid
TypeError: unsupported operand type(s) for |: 'int' and 'str'
```

**Comment by mab68** [comment]
This config DOES work:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            1:
                name: "h1"
                description: "host1 container"
                native_vlan: office
                acl_in: access-port-protect
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/c8adad5ece0d48defabcf73c2c840b480386ad25
