### ISSUE TITLE
Unhandled exception when certain fields are not strings

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1240]
Use this config:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 100
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: []
                ip_gw: 5.5
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            5:
                name: "trunk"
                description: "VLAN trunk to sw2"
                tagged_vlans: [office]
                acl_in: access-port-protect
```
Crash:
```
Nov 20 00:24:05 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 197, in _load_configs
    new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 168, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 121, in _dp_parser_v2
    vlans[vlan_ident] = VLAN(vlan_ident, dp_id, vlan_conf)
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 150, in __init__
    ip_gw = ipaddress.ip_address(btos(route['ip_gw']))
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 115, in btos
    return b_str.encode('utf-8').decode('utf-8', 'strict')
AttributeError: 'float' object has no attribute 'encode'
```

**Comment by mab68** [comment]
Same crash when the fields are empty
Config:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 100
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: 
                ip_gw: 
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            5:
                name: "trunk"
                description: "VLAN trunk to sw2"
                tagged_vlans: [office]
                acl_in: access-port-protect
```

**Comment by mab68** [comment]
Same error when faucet_vips is not a sequence of strings.
Config:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 100
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: [False, 5.5, 4584594]
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            5:
                name: "trunk"
                description: "VLAN trunk to sw2"
                tagged_vlans: [office]
                acl_in: access-port-protect
```
Error:
```
Nov 20 00:58:03 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 197, in _load_configs
    new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 168, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 121, in _dp_parser_v2
    vlans[vlan_ident] = VLAN(vlan_ident, dp_id, vlan_conf)
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 134, in __init__
    ipaddress.ip_interface(btos(ip)) for ip in self.faucet_vips]
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 134, in <listcomp>
    ipaddress.ip_interface(btos(ip)) for ip in self.faucet_vips]
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 115, in btos
    return b_str.encode('utf-8').decode('utf-8', 'strict')
AttributeError: 'bool' object has no attribute 'encode'
```
However, no error is thrown when
`        faucet_vips: []`
