### ISSUE TITLE
Unhandled exception when mac address is not valid

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1243]
Config:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 100
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: ""
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            5:
                name: "trunk"
                description: "VLAN trunk to sw2"
                tagged_vlans: [office]
                acl_in: access-port-protect
```
Crash (in a loop):
```
Nov 20 00:49:49 faucet INFO     Add new datapath DPID 1 (0x1)
Nov 20 00:49:49 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/netaddr/eui/__init__.py", line 442, in _set_value
    self._value = self._module.str_to_int(value)
  File "/usr/lib/python3.6/site-packages/netaddr/strategy/eui48.py", line 176, in str_to_int
    raise AddrFormatError('%r is not a supported MAC format!' % addr)
netaddr.core.AddrFormatError: '' is not a supported MAC format!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 342, in advertise
    flowmods = valve.advertise()
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 313, in advertise
    ofmsgs.extend(route_manager.advertise(vlan))
  File "/usr/lib/python3.6/site-packages/faucet/valve_route.py", line 890, in advertise
    other_vips))
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 291, in flood_pkt
    pkt = packet_builder(self, vid, *args)
  File "/usr/lib/python3.6/site-packages/faucet/valve_packet.py", line 460, in router_advert
    pkt.serialize()
  File "/usr/lib/python3.6/site-packages/ryu/lib/packet/packet.py", line 99, in serialize
    data = p.serialize(self.data, prev)
  File "/usr/lib/python3.6/site-packages/ryu/lib/packet/icmpv6.py", line 142, in serialize
    hdr += self.data.serialize()
  File "/usr/lib/python3.6/site-packages/ryu/lib/packet/icmpv6.py", line 385, in serialize
    hdr.extend(option.serialize())
  File "/usr/lib/python3.6/site-packages/ryu/lib/packet/icmpv6.py", line 451, in serialize
    addrconv.mac.text_to_bin(self.hw_src)))
  File "/usr/lib/python3.6/site-packages/ryu/lib/addrconv.py", line 32, in text_to_bin
    raise e
  File "/usr/lib/python3.6/site-packages/ryu/lib/addrconv.py", line 29, in text_to_bin
    return self._addr(text, **self._addr_kwargs).packed
  File "/usr/lib/python3.6/site-packages/netaddr/eui/__init__.py", line 387, in __init__
    self.value = addr
  File "/usr/lib/python3.6/site-packages/netaddr/eui/__init__.py", line 445, in _set_value
    % (value, self._module.version))
netaddr.core.AddrFormatError: address '' is not an EUIv48
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/89c9130a0e2e9656014369eae88fb5fba0cdf84e
