### ISSUE TITLE
Unhandled exception when router vlans is not iterable

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1245]
Config:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 100
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
routers:
    router-office-guest:
        vlans:
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            1:
                name: "h1"
                description: "host1 container"
                native_vlan: office
                acl_in: access-port-protect
```
Crash:
```
Nov 20 01:22:41 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 197, in _load_configs
    new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 168, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 136, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 515, in finalize_config
    resolve_vlan_names_in_routers()
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 490, in resolve_vlan_names_in_routers
    for vlan_name in router.vlans:
TypeError: 'NoneType' object is not iterable
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/issues/1273 duplicate.
