### ISSUE TITLE
Unhandled exception when dp_id is very big

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1246]
Config:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 100
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
    guest:
        vid: 200
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['10.0.200.254/24', '2001:200::1/64', 'fe80::c00:00ff:fe00:2001/64']
dps:
    sw1:
        dp_id: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            1:
                name: "h1"
                description: "host1 container"
                native_vlan: office
                acl_in: access-port-protect
```
Error:
```
Nov 20 01:40:42 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 204, in _load_configs
    self._apply_configs(new_dps)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 184, in _apply_configs
    valve.update_config_metrics(self.metrics)
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 682, in update_config_metrics
    self.dp.dp_id)
  File "/usr/lib/python3.6/site-packages/prometheus_client/core.py", line 703, in set
    self._value.set(float(value))
OverflowError: int too large to convert to float
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/59b656cfe5b341a695bf87e8d13cd9dbdff8fe24
