### ISSUE TITLE
Unhandled exception when dp interfaces is not valid

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1247]
Config:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 100
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
    guest:
        vid: 200
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['10.0.200.254/24', '2001:200::1/64', 'fe80::c00:00ff:fe00:2001/64']
dps:
    sw1:
        dp_id: 0x1
        hardware: 
        proactive_learn: True
        interfaces:
```
Error:
```
Nov 20 02:03:31 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 197, in _load_configs
    new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 168, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 130, in _dp_parser_v2
    _dp_add_ports(dp, dp_conf, dp_id, vlans)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 106, in _dp_add_ports
    for port_num, port_conf in list(ports_conf.items()):
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by mab68** [comment]
Config:
```
include:
    - acls.yaml
vlans:
    office:
        vid: 100
        description: "office network"
        acl_in: office-vlan-protect
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
        routes:
            - route:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
    guest:
        vid: 200
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['10.0.200.254/24', '2001:200::1/64', 'fe80::c00:00ff:fe00:2001/64']
dps:
    sw1:
        dp_id: 0x1
        hardware: 
        proactive_learn: True
        interfaces: {'5': 5}
```
Error:
```
Nov 20 02:04:49 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 197, in _load_configs
    new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 168, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 130, in _dp_parser_v2
    _dp_add_ports(dp, dp_conf, dp_id, vlans)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 107, in _dp_add_ports
    port = _dp_parse_port(dp_id, port_num, port_conf, vlans)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 99, in _dp_parse_port
    assert port.vlans() or port.stack, '%s must have a VLAN or be a stack port' % port
  File "/usr/lib/python3.6/site-packages/faucet/port.py", line 99, in __str__
    return 'Port %u' % self.number
TypeError: %u format: a number is required, not NoneType
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d5cd6bf89d6142739c7ebb4ea7cdcdb6a8c62198
