### ISSUE TITLE
Unhandled exception when vlans is not iterable

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1249]
Config:
```
include:
    - acls.yaml
vlans: 1976-07-31
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        proactive_learn: True
        interfaces:
            1:
                name: "h1"
                description: "host1 container"
                native_vlan: office
                acl_in: access-port-protect
```
Error:
```
Nov 20 03:01:31 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 197, in _load_configs
    new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 157, in _config_parser_v2
    config_hashes, config_path, logname, top_confs):
  File "/usr/lib/python3.6/site-packages/faucet/config_parser_util.py", line 79, in dp_include
    new_top_confs[conf_name].update(conf.pop(conf_name, {}))
TypeError: 'datetime.date' object is not iterable
```

**Comment by mab68** [comment]
Closing this is the same error as #1248.
