### ISSUE TITLE
Unhandled exception when deleting a port from the config

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#1271]
```
Nov 21 06:55:16 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 204, in _load_configs
    self._apply_configs(new_dps)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 159, in _apply_configs
    cold_start, flowmods = valve.reload_config(new_dp)
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 885, in reload_config
    new_dp, self.dp.get_config_changes(self.logger, new_dp))
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 722, in get_config_changes
    logger, new_dp, changed_vlans, changed_acls)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 687, in _get_port_config_changes
    logger.info('deleted ports: %s', deleted_ports)
TypeError: info() takes 2 positional arguments but 3 were given
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/2058b605fefe0e7cc656a0c1b5a56566b65c1d7c
