### ISSUE TITLE
Unhandled Exception when interface port isn't a number

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1280]
Config:
```
vlans:
    office:
        vid: 100
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            testing:
                native_vlan: office
```
Error:
```
Nov 26 22:59:21 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 197, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 56, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 200, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 166, in _dp_parser_v2
    _dp_add_ports(dp, dp_conf, dp_id, vlans)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 148, in _dp_add_ports
    _dp_add_vlan(dp, vlan)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 99, in _dp_add_vlan
    if vlan not in dp.vlans:
  File "/usr/lib/python3.6/site-packages/faucet/conf.py", line 99, in __hash__
    dyn_hash = self.conf_hash(dyn=False, subconf=True)
  File "/usr/lib/python3.6/site-packages/faucet/conf.py", line 94, in conf_hash
    str, self._conf_keys(self, dyn=dyn, subconf=subconf, ignore_keys=ignore_keys)))))
  File "/usr/lib/python3.6/site-packages/faucet/port.py", line 102, in __repr__
    return self.__str__()
  File "/usr/lib/python3.6/site-packages/faucet/port.py", line 99, in __str__
    return 'Port %u' % self.number
TypeError: %u format: a number is required, not str
```

**Comment by mab68** [comment]
No exception is thrown when port is negative or a float.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/29b6c78ae2ffa0cd1143bf5a9d4682b4e9c3126f
