### ISSUE TITLE
Unhandled exception when acl dl_type is not a valid int

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1305]
Config:
```
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                native_vlan: 2040
                acl_in: 1
vlans:
    name:
        vid: 2040
acls:
    1:
        - rule:
            dl_type: 06.5
```
Error:
```
Nov 27 21:47:55 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 198, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 50, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 151, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 125, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 556, in finalize_config
    resolve_acls()
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 523, in resolve_acls
    build_acl(port.acl_in, vid=1)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 507, in build_acl
    vlan_vid=vid)
  File "/usr/lib/python3.6/site-packages/faucet/valve_acl.py", line 140, in build_acl_ofmsgs
    rule_conf, acl_allow_inst, meters, port_num, vlan_vid)
  File "/usr/lib/python3.6/site-packages/faucet/valve_acl.py", line 128, in build_acl_entry
    acl_match = valve_of.match_from_dict(match_dict)
  File "/usr/lib/python3.6/site-packages/faucet/valve_of.py", line 386, in match_from_dict
    value = convert[key](value)
  File "/usr/lib/python3.6/site-packages/ryu/lib/ofctl_utils.py", line 266, in str_to_int
    return int(str(str_num), 0)
ValueError: invalid literal for int() with base 0: '6.5'
```

**Comment by anarkiwi** [comment]
Can I suggest experimenting with:
https://github.com/HypothesisWorks/hypothesis-python (or similar).

And generating YAML files based on a loose scheme, that cause our parser to
crash?

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d606e9be245e643651a3e6574d4f14e29598c6ac
