### ISSUE TITLE
isfragment() check has exception on GRE packet

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#1318]
Nov 30 07:32:46 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/faucet/faucet.py", line 417, in packet_in_handler
    flowmods = valve.rcv_packet(other_valves, pkt_meta)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 756, in rcv_packet
    pkt_meta.reparse_ip(pkt_meta.eth_type)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_packet.py", line 518, in reparse_ip
    if self.isfragment():
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_packet.py", line 509, in isfragment
    dpkt_ip = dpkt.ethernet.Ethernet(self.data)
  File "/usr/local/lib/python3.5/dist-packages/dpkt/ethernet.py", line 75, in __init__
    if self.data:
  File "/usr/local/lib/python3.5/dist-packages/dpkt/ip.py", line 93, in __len__
    return self.__hdr_len__ + len(self.opts) + len(self.data)
  File "/usr/local/lib/python3.5/dist-packages/dpkt/dpkt.py", line 102, in __len__
    return self.__hdr_len__ + len(self.data)
  File "/usr/local/lib/python3.5/dist-packages/dpkt/dpkt.py", line 102, in __len__
    return self.__hdr_len__ + len(self.data)
  File "/usr/local/lib/python3.5/dist-packages/dpkt/ip.py", line 93, in __len__
    return self.__hdr_len__ + len(self.opts) + len(self.data)
  File "/usr/local/lib/python3.5/dist-packages/dpkt/gre.py", line 109, in __len__
    opt_fmtlen = struct.calcsize(b''.join(self.opt_fields_fmts()[1]))
TypeError: sequence item 0: expected a bytes-like object, str found

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d606e9be245e643651a3e6574d4f14e29598c6ac
