### ISSUE TITLE
Unhandled exception when acl rule isn't spelt correctly

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1319]
Config:
```
acls:
    office-vlan-protect:
        - 2ule:
            dl_type: 0x800
vlans:
    office:
        vid: 100
        acl_in: office-vlan-protect
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                native_vlan: office
```
Error:
```
Nov 30 22:30:45 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 198, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 188, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 151, in _dp_parser_v2
    acl = ACL(acl_ident, dp_id, acl_conf)
  File "/usr/lib/python3.6/site-packages/faucet/acl.py", line 46, in __init__
    self.rules = [x['rule'] for x in rules]
  File "/usr/lib/python3.6/site-packages/faucet/acl.py", line 46, in <listcomp>
    self.rules = [x['rule'] for x in rules]
KeyError: 'rule'
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d606e9be245e643651a3e6574d4f14e29598c6ac
