### ISSUE TITLE
Unhandled exception with config file containing invalid utf-8 characters

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1320]
Config:
[faucet.txt](https://github.com/faucetsdn/faucet/files/1520030/faucet.txt)
Error:
```
Dec 01 00:49:14 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 198, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 42, in dp_parser
    conf = config_parser_util.read_config(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser_util.py", line 36, in read_config
    conf = yaml.safe_load(stream)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/usr/lib/python3.6/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 0: invalid continuation byte
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/df89495fa7ef8a2cd5d3fbcfcf7faa4dbb604442
