### ISSUE TITLE
Unhanled exception when acl rule ipv4 address subnet mask is too big

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1324]
Config:
```
acls:
    office-vlan-protect:
        - rule:
            dl_type: 0x800
            ipv4_src: 10.0.100.0/24
            ipv4_src: 10.0.200.0/64
            actions:
                allow: 0
vlans:
    office:
        vid: 100
        acl_in: office-vlan-protect
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                native_vlan: office
```
Error:
```
Dec 01 01:20:05 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 928, in __init__
    implicit_prefix, flags)
  File "/usr/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 821, in parse_ip_network
    % module.family_name)
netaddr.core.AddrFormatError: invalid prefix for IPv4 address!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 198, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 188, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 162, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 560, in finalize_config
    resolve_acls()
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 521, in resolve_acls
    build_acl(vlan.acl_in, vid=1)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 511, in build_acl
    vlan_vid=vid)
  File "/usr/lib/python3.6/site-packages/faucet/valve_acl.py", line 140, in build_acl_ofmsgs
    rule_conf, acl_allow_inst, meters, port_num, vlan_vid)
  File "/usr/lib/python3.6/site-packages/faucet/valve_acl.py", line 128, in build_acl_entry
    acl_match = valve_of.match_from_dict(match_dict)
  File "/usr/lib/python3.6/site-packages/faucet/valve_of.py", line 386, in match_from_dict
    value = convert[key](value)
  File "/usr/lib/python3.6/site-packages/ryu/lib/ofctl_utils.py", line 165, in to_match_ip
    ip = netaddr.ip.IPNetwork(value)
  File "/usr/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 938, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % addr)
netaddr.core.AddrFormatError: invalid IPNetwork 10.0.200.0/64
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d606e9be245e643651a3e6574d4f14e29598c6ac
