### ISSUE TITLE
Unhandled exception when acl attribute doesn't have any items

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1326]
Config:
```
acls:
    office-vlan-protect:
        - rule:
            dl_type: 0x800
            ipv4_src: 10.0.100.0/24
            ipv4_src: 10.0.200.0/24
            actions:
          0     allow: 0
vlans:
    office:
        vid: 100
        acl_in: office-vlan-protect
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                native_vlan: office
```
Error:
```
Dec 01 01:28:02 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 198, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 188, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 162, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 559, in finalize_config
    resolve_names_in_acls()
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 491, in resolve_names_in_acls
    for action_name, action_conf in list(attrib_value.items()):
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d606e9be245e643651a3e6574d4f14e29598c6ac
