### ISSUE TITLE
Unhanled exception when udp_src is not a valid int

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1328]
Config:
```
acls:
    access-port-protect:
        - rule:
            dl_type: 0x800
            nw_proto: 17
            udp_src: v7
            udp_dst: 68
            actions:
                allow: 0
vlans:
    office:
        vid: 100
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                native_vlan: office
                acl_in: access-port-protect
```
Error:
```
Dec 01 01:38:13 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 198, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 188, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 162, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 560, in finalize_config
    resolve_acls()
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 527, in resolve_acls
    build_acl(port.acl_in, vid=1)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 511, in build_acl
    vlan_vid=vid)
  File "/usr/lib/python3.6/site-packages/faucet/valve_acl.py", line 140, in build_acl_ofmsgs
    rule_conf, acl_allow_inst, meters, port_num, vlan_vid)
  File "/usr/lib/python3.6/site-packages/faucet/valve_acl.py", line 128, in build_acl_entry
    acl_match = valve_of.match_from_dict(match_dict)
  File "/usr/lib/python3.6/site-packages/faucet/valve_of.py", line 386, in match_from_dict
    value = convert[key](value)
  File "/usr/lib/python3.6/site-packages/ryu/lib/ofctl_utils.py", line 203, in to_match_masked_int
    return str_to_int(value)
  File "/usr/lib/python3.6/site-packages/ryu/lib/ofctl_utils.py", line 266, in str_to_int
    return int(str(str_num), 0)
ValueError: invalid literal for int() with base 0: 'v7'
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d606e9be245e643651a3e6574d4f14e29598c6ac
