### ISSUE TITLE
Unhandled exception when vlan routes cannot be found

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1349]
Config:
```
vlans:
    office:
        vid: 100
        routes:
            - 2oute:
                ip_dst: '192.168.0.0/24'
                ip_gw: '10.0.100.2'
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                native_vlan: office
```
Error:
```
Dec 04 02:02:28 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 208, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 188, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 149, in _dp_parser_v2
    vlans[vlan_ident] = VLAN(vlan_ident, dp_id, vlan_conf)
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 131, in __init__
    super(VLAN, self).__init__(_id, dp_id, conf)
  File "/usr/lib/python3.6/site-packages/faucet/conf.py", line 42, in __init__
    self.check_config()
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 173, in check_config
    self.routes = [route['route'] for route in self.routes]
  File "/usr/lib/python3.6/site-packages/faucet/vlan.py", line 173, in <listcomp>
    self.routes = [route['route'] for route in self.routes]
KeyError: 'route'
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/438b7a42ffb0a9490993c7f1f31ec81b85795bec
