### ISSUE TITLE
Unhandled exception when trying to read a file that does not have the correct permissions

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1350]
Error:
```
Dec 04 03:41:44 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 208, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 42, in dp_parser
    conf = config_parser_util.read_config(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser_util.py", line 35, in read_config
    with open(config_file, 'r') as stream:
PermissionError: [Errno 13] Permission denied: '/etc/ryu/faucet/faucet.yaml'
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/314052f8668e71695d2aff37c0bd585322fd6812
