### ISSUE TITLE
Unhandled exception when dp_conf is doesn't form properly

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1352]
Config:
```
vlans:
    office:
        vid: 100
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                description: "host1 container"
    0           native_vlan: office
```
Error:
```
Dec 04 03:54:40 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 208, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 188, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 144, in _dp_parser_v2
    dp = DP(identifier, dp_conf.get('dp_id', None), dp_conf)
AttributeError: 'str' object has no attribute 'get'
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/1582fbff68fdefc0170a5e25a01684e5a0a5938b
