### ISSUE TITLE
Unhandled exception when faucet doesn't have permission to write to the logs

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1386]
Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 105, in get_logger
    logger_handler = logging.StreamHandler(stream_handlers[logfile])
KeyError: '/var/log/ryu/faucet/faucet.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 11, in <module>
    load_entry_point('ryu==4.20', 'console_scripts', 'ryu-manager')()
  File "/usr/local/lib/python3.5/dist-packages/ryu/cmd/manager.py", line 101, in main
    services.extend(app_mgr.instantiate_apps(**contexts))
  File "/usr/local/lib/python3.5/dist-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
    self._instantiate(app_name, cls, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ryu/base/app_manager.py", line 495, in _instantiate
    app = cls(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/faucet/faucet.py", line 131, in __init__
    self.logname, self.logfile, self.loglevel, 0)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 107, in get_logger
    logger_handler = WatchedFileHandler(logfile)
  File "/usr/lib/python3.5/logging/handlers.py", line 434, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/ryu/faucet/faucet.log'
```

**Comment by aappachi** [comment]
Josh,
can i take this bug?
-nambi

**Comment by anarkiwi** [comment]
Sure.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d79bb9186bfbd41a78468b07003d4b6e466d7b5e
