### ISSUE TITLE
Unhandled exception inside faucet_experimental_event

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1388]
When I try boot up faucet on my network with latest faucet@master I get an exception when binding to the event socket. I suspect there is a case we aren't handling where self.socket_path can be None.

> Dec 11 16:07:39 faucet.exception ERROR    Unhandled exception, killing RYU
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 34, in __koe
>     func(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/faucet/faucet.py", line 131, in start
>     notifier_thread = self.notifier.start()
>   File "/usr/local/lib/python3.5/dist-packages/faucet/faucet_experimental_event.py", line 60, in start
>     StreamServer((self.socket_path, None), self._loop).serve_forever)
>   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/hub.py", line 126, in __init__
>     self.server = eventlet.listen(listen_info)
>   File "/usr/local/lib/python3.5/dist-packages/eventlet/convenience.py", line 46, in listen
>     sock.bind(addr)
> TypeError: an integer is required (got type NoneType)

**Comment by gizmoguy** [comment]
Ok the issue is that faucet_experimental_event doesn't currently work on systems where faucet is running as an unprivileged user.

socket_path will default to /var/run/faucet/faucet.sock. On my systems I run faucet as a user that doesn't have write access to /var/run/ so it can't create this directory and since it doesn't exist eventlet will crash trying to listen on a non-existent socket.
