### ISSUE TITLE
Unhandled exception when dp_id forms a string

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1399]
Config:
```
vlans:
    office:
        vid: 100
dps:
    sw1:
#        dp_id: 0x1
        interfaces:
            1:
                native_vlan: office
```
Error:
```
Dec 13 20:29:41 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 217, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 189, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 145, in _dp_parser_v2
    dp = DP(identifier, dp_conf.get('dp_id', None), dp_conf)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 192, in __init__
    super(DP, self).__init__(_id, dp_id, conf)
  File "/usr/lib/python3.6/site-packages/faucet/conf.py", line 42, in __init__
    self.check_config()
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 203, in check_config
    assert self.dp_id > 0 and self.dp_id <= 2**64-1, 'DP ID %s not in valid range' % self.dp_id
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by mab68** [comment]
Config:
```
vlans:
    office:
        vid: 100
dps:
    sw1:
        dp_id: &x1
        interfaces:
            1:
                native_vlan: office
```

**Comment by mab68** [comment]
config:
```
vlans:
    office:
        vid: 100
dps:
    sw1:
        name: test
        interfaces:
            1:
                native_vlan: office
```
