### ISSUE TITLE
Unhandled exception when acl key forms a dictionary

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1400]
Config:
```
acls:
?   office-vlan-protect:
        - rule:
            actions:
                allow: 1
vlans:
    office:
        vid: 100
        acl_in: office-vlan-protect
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                native_vlan: office
```
Error:
```
Dec 13 20:31:55 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 217, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 42, in dp_parser
    conf = config_parser_util.read_config(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser_util.py", line 50, in read_config
    conf = yaml.load(stream.read())
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser_util.py", line 32, in no_duplicates_constructor
    if key in keys:
TypeError: unhashable type: 'dict'
```

**Comment by mab68** [comment]
Config:
```
acls:
 ?  office-vlan-protect:
        - rule:
            actions:
                allow: 1
vlans:
    office:
        vid: 100
        acl_in: office-vlan-protect
dps:
    sw1:
        dp_id: 0x1
        interfaces:
            1:
                native_vlan: office
```
Error:
```
Dec 13 20:36:21 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 217, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 42, in dp_parser
    conf = config_parser_util.read_config(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser_util.py", line 50, in read_config
    conf = yaml.load(stream.read())
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser_util.py", line 35, in no_duplicates_constructor
    return loader.construct_mapping(node, deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser_util.py", line 32, in no_duplicates_constructor
    if key in keys:
TypeError: unhashable type: 'dict'
```
