### ISSUE TITLE
Unhandled exception when acl mirror port name forms a dict

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#1406]
Config:
```
vlans:
    100:
acls:
    101:
        - rule:
            dl_dst: "0e:00:00:00:02:02"
            actions:
               mirror: 
                    port: 1
dps:
    switch1:
        dp_id: 0xcafef00d
        hardware: 'Open vch'
        interfaces:
            1:
                native_vlan: 100
                acl_in: 101
```
Error:
```
Dec 13 21:07:14 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 217, in _load_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 189, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 163, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 566, in finalize_config
    resolve_names_in_acls()
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 499, in resolve_names_in_acls
    acl, action_conf)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 439, in resolve_mirror
    port_no = resolve_port_no(port_name)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 389, in resolve_port_no
    if port_name in port_by_name:
TypeError: unhashable type: 'dict'
```

**Comment by mab68** [comment]
Fixed in 612967a
