### ISSUE TITLE
Unstacked dataplane causes config exception

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1534]
The attached config generates the following error on load. According to chat, this should not be the case -- e.g., it should be valid to have an unreachable switch (no stacking connection). Note that this is not actually a "problem" that's blocking me at the moment -- rather it's just unexpected behavior.

Jan 18 23:21:42 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 220, in _load_configs
    self._apply_configs(new_dps)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 200, in _apply_configs
    valve = self._apply_configs_new(dp_id, new_dp)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 182, in _apply_configs_new
    return valve_cl(new_dp, self.logname, self.notifier)
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 104, in __init__
    self.dp.shortest_path_to_root, dp.shortest_path_port)
  File "/usr/lib/python3.6/site-packages/faucet/valve_flood.py", line 206, in __init__
    my_root_distance = len(dp_shortest_path_to_root())
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 366, in shortest_path_to_root
    return self.shortest_path(root_dp.name)
  File "/usr/lib/python3.6/site-packages/faucet/dp.py", line 359, in shortest_path
    self.stack['graph'], self.name, dest_dp)
  File "/usr/lib/python3.6/site-packages/networkx/algorithms/shortest_paths/generic.py", line 142, in shortest_path
    paths = nx.bidirectional_shortest_path(G, source, target)
  File "/usr/lib/python3.6/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 226, in bidirectional_shortest_path
    results = _bidirectional_pred_succ(G, source, target)
  File "/usr/lib/python3.6/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 294, in _bidirectional_pred_succ
    raise nx.NetworkXNoPath("No path between %s and %s." % (source, target))
networkx.exception.NetworkXNoPath: No path between SWSEC0B and SWPRI2.
[faucet.yaml.txt](https://github.com/faucetsdn/faucet/files/1644799/faucet.yaml.txt)

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/eee957cbaecb269ba81c80712f9853f358e7bfdb
