### ISSUE TITLE
Verify that port is configured before checking opstatus_reconf (port_status_handler)

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#1593]
I received an OpenFlow port_status ADD message for port that is not in the config file. There is nothing defending the new `opstatus_reconf` check in `port_status_handler`:

```
Jan 31 13:11:59.202 zof.faucet CRITICAL Fatal Exception caught while handling "message": {'type': 'PORT_STATUS', 'time': '1517429519.196578000', 'xid': 0, 'version': 4, 'conn_id': 2, 'datapath_id': '00:00:00:00:00:00:00:01', 'msg': {'reason': 'ADD', 'port_no': 5, 'hw_addr': '42:07:9c:89:7a:e2', 'name': 's1-eth5', 'config': ['PORT_DOWN'], 'state': ['LINK_DOWN'], 'ethernet': {'curr': ['10GB_FD', 'COPPER'], 'advertised': [], 'supported': [], 'peer': [], 'curr_speed': 10000000, 'max_speed': 0}, 'properties': []}, 'datapath': '<zof.Datapath 00:00:00:00:00:00:00:01>'}
Traceback (most recent call last):
  File "/Users/bfish/code/pylibofp/zof/controllerapp.py", line 62, in handle_event
    handler(event, self)
  File "/Users/bfish/code/pylibofp/zof/handler.py", line 77, in __call__
    self.callback(event)
  File "/Users/bfish/code/faucet/faucet/zof_faucet.py", line 260, in port_status
    flowmods = valve.port_status_handler(port_no, reason, link_up)
  File "/Users/bfish/code/faucet/faucet/valve.py", line 321, in port_status_handler
    if self.dp.ports[port_no].opstatus_reconf:
KeyError: 5
```

At the top of port_status_handler in valve.py, a guard could be added (or this guard could be added in faucet.py if you don't want to export the port status of unconfigured ports to prometheus).

```
if port_no not in self.dp.ports:
    self.logger.info('Ignoring port:%u not present in configuration file' % port_no)
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/242bf436e893663a2809d4e848e4c1a55f3783a9
