### ISSUE TITLE
Exception when learn host with stack and non-stack in the same config

### ISSUE THREAD

**Issue by trungdtbk** [faucetsdn/faucet#1595]
When a stack DP learns a host originating from a non-stack DP, we got the following exception.
```
Feb 02 04:38:28 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/home/trungth/git/faucet/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/home/trungth/git/faucet/faucet/faucet.py", line 466, in packet_in_handler
    flowmods = valve.rcv_packet(other_valves, pkt_meta)
  File "/home/trungth/git/faucet/faucet/valve.py", line 853, in rcv_packet
    ofmsgs.extend(self._learn_host(other_valves, pkt_meta))
  File "/home/trungth/git/faucet/faucet/valve.py", line 717, in _learn_host
    other_valves, pkt_meta)
  File "/home/trungth/git/faucet/faucet/valve_flood.py", line 368, in edge_learn_port
    return self.shortest_path_port(edge_dp.name)
  File "/home/trungth/git/faucet/faucet/dp.py", line 409, in shortest_path_port
    shortest_path = self.shortest_path(dest_dp)
  File "/home/trungth/git/faucet/faucet/dp.py", line 393, in shortest_path
    self.stack['graph'], self.name, dest_dp)
  File "/home/trungth/.local/lib/python3.5/site-packages/networkx/algorithms/shortest_paths/generic.py", line 142, in shortest_path
    paths = nx.bidirectional_shortest_path(G, source, target)
  File "/home/trungth/.local/lib/python3.5/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 223, in bidirectional_shortest_path
    raise nx.NodeNotFound(msg.format(source, target))
networkx.exception.NodeNotFound: Either source agg1 or target acc1 is not in G
```

**Comment by anarkiwi** [comment]
Thank you for reporting this!

https://github.com/faucetsdn/faucet/commit/7672c3017134def1ad18a1e2f57bf0c7b4d48980
