### ISSUE TITLE
Unhandled exception if an OpenFlow1.0 switch connects to Faucet

### ISSUE THREAD

**Issue by KitL** [faucetsdn/faucet#1665]
```
chrislorier@kit:~/faucet$ faucet
loading app faucet.faucet
loading app ryu.controller.ofp_handler
instantiating app None of DPSet
creating context dpset
creating context faucet_experimental_api
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app faucet.faucet of Faucet


unsupported version 0x1. If possible, set the switch to use one of the versions [4]
Error in the datapath None from ('127.0.0.1', 52866)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ryu/lib/hub.py", line 59, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ryu/controller/controller.py", line 522, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.5/dist-packages/ryu/controller/controller.py", line 440, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.5/dist-packages/ryu/controller/controller.py", line 194, in deactivate
    method(self)
  File "/usr/local/lib/python3.5/dist-packages/ryu/controller/controller.py", line 343, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.5/dist-packages/ryu/controller/ofp_handler.py", line 182, in hello_handler
    self._hello_failed(datapath, error_desc)
  File "/usr/local/lib/python3.5/dist-packages/ryu/controller/ofp_handler.py", line 68, in _hello_failed
    datapath.send_msg(error_msg)
  File "/usr/local/lib/python3.5/dist-packages/ryu/controller/controller.py", line 409, in send_msg
    msg.serialize()
  File "/usr/local/lib/python3.5/dist-packages/ryu/ofproto/ofproto_parser.py", line 270, in serialize
    self._serialize_body()
  File "/usr/local/lib/python3.5/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 300, in _serialize_body
    self.buf += self.data
TypeError: can't concat str to bytearray
```

Not sure if this occurs with other versions as well.

**Comment by byllyfish** [comment]
The Ryu _hello_failed method passes a string to construct an OFPError message field that expects bytes.  This is safe in Python2, but fails in Python3.

Here is a patch that fixes the issue for me, and includes the source IP of the switch in the log message:

```diff
diff --git a/ryu/controller/ofp_handler.py b/ryu/controller/ofp_handler.py
index 4f439c2e..3f4d2be9 100644
--- a/ryu/controller/ofp_handler.py
+++ b/ryu/controller/ofp_handler.py
@@ -60,11 +60,11 @@ class OFPHandler(ryu.base.app_manager.RyuApp):
         return hub.spawn(self.controller)
 
     def _hello_failed(self, datapath, error_desc):
-        self.logger.error(error_desc)
+        self.logger.error('%s %r', error_desc, datapath.address)
         error_msg = datapath.ofproto_parser.OFPErrorMsg(datapath)
         error_msg.type = datapath.ofproto.OFPET_HELLO_FAILED
         error_msg.code = datapath.ofproto.OFPHFC_INCOMPATIBLE
-        error_msg.data = error_desc
+        error_msg.data = error_desc.encode('ascii')
         datapath.send_msg(error_msg)
 
     @set_ev_handler(ofp_event.EventOFPHello, HANDSHAKE_DISPATCHER)

```

This doesn't entirely fix the issue. OVS 2.7 replies with BAD_REQUEST for the OFPError message. Ryu keeps the connection open in the HANDSHAKE_DISPATCHER state. 

Ryu still services echo requests and I can see PacketIn's still being sent over the still open connection. I assume Faucet doesn't see the packets, because it's only listening for PacketIn's in the MAIN_DISPATCHER state.

I added a datapath.close() to the end of _hello_failed, but this prevents the OFPError message from being sent; the send queue is not flushed.

**Comment by anarkiwi** [comment]
Looks like there's not much we can do on the FAUCET side. Seems like we should open a Ryu bug?

**Comment by byllyfish** [comment]
I will file a ryu bug for the uncaught exception with the above fix.

I can also file a ryu bug for leaving the OF 1.0 connection open.  If this is fixed, your logs will fill with "unsupported version 0x1." messages as the 1.0 switch reconnects.

**Comment by anarkiwi** [comment]
Thank you sir both counts. Yes please - we do this also if we get a switch we don't have in our config file (it will repeatedly reconnect and we will repeatedly hang up on it).
