### ISSUE TITLE
config reloads while BGP is active are not safe

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#1682]

**Comment by anarkiwi** [comment]
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ryu/lib/hub.py", line 59, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 256, in start
    self._run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/core.py", line 238, in _run
    server_thread.wait()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 175, in wait
    return self._exit_event.wait()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/event.py", line 121, in wait
    return hubs.get_hub().switch()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 354, in _listen_socket_lo
op
    sock, client_address = s.accept()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 220, in accept
    timeout_exc=socket.timeout("timed out"))
  File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 203, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
eventlet.hubs.IOClosed: [Errno 107] Operation on closed file

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/fba28c6b65ceb226a4afbc6ebdd028226145ff9c
