### ISSUE TITLE
unhandled exception: TypeError: int() argument must be a string, a bytes-like object or a number, not 'HostCacheEntry'

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#1768]
```
Mar 12 17:44:58 faucet.valve INFO     DPID 260367054848311 (0xeccd6dd0c137) port 48 reconfigured (--- a
+++ b
{
 'acl_in': None,
 'acls_in': None,
 'enabled': True,
 'hairpin': False,
 'lacp': 0,
 'lldp_beacon': {},
 'loop_protect': False,
 'max_hosts': 255,
-'mirror': None,
+'mirror': [47],
 'native_vlan': VLAN 4090 vid:4090 ports:Port 1,Port 2,Port 3,Port 4,Port 5,Port 6,Port 7,Port 8,Port 9,Port 10,Port 11,Port 12,Port 13,Port 14,Port 15,Port 16,Port 17,Port 18,Port 19,Port 20,Port 21,Port 22,Port 23,Port 24,Port 25,Port 26,Port 48,
 'number': 48,
 'opstatus_reconf': True,
 'output_only': False,
 'permanent_learn': True,
 'receive_lldp': False,
 'stack': None,
 'tagged_vlans': [],
 'unicast_flood': True,
@@  @@
})
Mar 12 17:44:58 faucet.valve INFO     DPID 260367054848311 (0xeccd6dd0c137) ports changed/added: {48, 1, 2, 47}
Mar 12 17:44:58 faucet.valve INFO     DPID 260367054848311 (0xeccd6dd0c137) Port 48 down
Mar 12 17:44:58 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 139, in reload_config
    self.config_file, delete_dp=self._delete_deconfigured_dp)
  File "/usr/lib/python3.6/site-packages/faucet/valves_manager.py", line 138, in request_reload_configs
    self.load_configs(new_config_file, delete_dp=delete_dp)
  File "/usr/lib/python3.6/site-packages/faucet/valves_manager.py", line 118, in load_configs
    ofmsgs = valve.reload_config(new_dp)
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 1111, in reload_config
    new_dp, self.dp.get_config_changes(self.logger, new_dp))
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 1069, in _apply_config_changes
    ofmsgs.extend(self.ports_delete(changed_ports))
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 648, in ports_delete
    ofmsgs.extend(self._port_delete_flows_state(port))
  File "/usr/lib/python3.6/site-packages/faucet/valve.py", line 539, in _port_delete_flows_state
    match=eth_src_table.match(eth_src=eth_src)))
  File "/usr/lib/python3.6/site-packages/faucet/valve_table.py", line 48, in match
    match = valve_of.match(match_dict)
  File "/usr/lib/python3.6/site-packages/faucet/valve_of.py", line 350, in match
    return parser.OFPMatch(**match_fields)
  File "/usr/lib/python3.6/site-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 893, in __init__
    in kwargs.items()]
  File "/usr/lib/python3.6/site-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 892, in <listcomp>
    fields = [ofproto.oxm_from_user(k, v) for (k, v)
  File "/usr/lib/python3.6/site-packages/ryu/ofproto/oxx_fields.py", line 72, in _from_user
    value = t.from_user(value)
  File "/usr/lib/python3.6/site-packages/ryu/lib/addrconv.py", line 32, in text_to_bin
    raise e
  File "/usr/lib/python3.6/site-packages/ryu/lib/addrconv.py", line 29, in text_to_bin
    return self._addr(text, **self._addr_kwargs).packed
  File "/usr/lib/python3.6/site-packages/netaddr/eui/__init__.py", line 387, in __init__
    self.value = addr
  File "/usr/lib/python3.6/site-packages/netaddr/eui/__init__.py", line 447, in _set_value
    if 0 <= int(value) <= self._module.max_int:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'HostCacheEntry'
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/442f47daa13610ef6e4acdce4f1ca9811a9b2800

Sorry about that - we didn't test the case of deleting a port with permanent learn that had cache entries to clear. Fixed in master.
