### ISSUE TITLE
interface_ranges with single element fails

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#1843]
The following configuration fails to load.

```yaml
dps:
    sw1:
        dp_id: 0x1
        interface_ranges:
            1:     # parsed as an integer
                native_vlan: 1
```

PyYAML will parse the "1" as an integer, but the config_parser code for interface_ranges expects port_range to be a string. 

```
Traceback (most recent call last):
  File "/Users/bfish/code/faucet/faucet/valve_util.py", line 41, in __koe
    func(*args, **kwargs)
  File "/Users/bfish/code/faucet/faucet/faucet.py", line 100, in _load_configs
    new_config_file, delete_dp=self._delete_deconfigured_dp)
  File "/Users/bfish/code/faucet/faucet/valves_manager.py", line 108, in load_configs
    new_dps = self.parse_configs(new_config_file)
  File "/Users/bfish/code/faucet/faucet/valves_manager.py", line 88, in parse_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/Users/bfish/code/faucet/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/Users/bfish/code/faucet/faucet/config_parser.py", line 200, in _config_parser_v2
    top_confs['vlans'])
  File "/Users/bfish/code/faucet/faucet/config_parser.py", line 162, in _dp_parser_v2
    _dp_add_ports(dp, dp_conf, dp_id, vlans)
  File "/Users/bfish/code/faucet/faucet/config_parser.py", line 119, in _dp_add_ports
    for range_ in re.findall(r'(\d+-\d+)', port_range):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/cfb6cab6a32799eaf1254ae90606037a4f4435e2
