### ISSUE TITLE
Unit Test Case FaucetStackStringOfDPUntaggedTest would not pass for certain dp port numbers

### ISSUE THREAD

**Issue by chihhoyen** [faucetsdn/faucet#2106]
If using any DP port numbers other than 1 to 4, **FaucetStackStringOfDPUntaggedTest** would not pass.

For example, if DP port numbers are from 1 to 4, this test case would pass.
```
test_untagged (faucet_mininet_test_unit.FaucetStackStringOfDPUntaggedTest)
All untagged hosts in stack topology can reach each other. ... ok

----------------------------------------------------------------------
Ran 1 test in 53.594s

OK
```
However, if DP port numbers are from 37 to 40 (or consecutive numbers other than 1 to 4), this test would fail as below:
```
test_untagged (faucet_mininet_test_unit.FaucetStackStringOfDPUntaggedTest)
All untagged hosts in stack topology can reach each other. ... FAIL

======================================================================
FAIL: test_untagged (faucet_mininet_test_unit.FaucetStackStringOfDPUntaggedTest)
All untagged hosts in stack topology can reach each other.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/faucet_mininet_test_unit.py", line 5471, in test_untagged
    self.verify_stack_hosts()
  File "/faucet-src/tests/faucet_mininet_test_unit.py", line 5361, in verify_stack_hosts
    self.retry_net_ping()
  File "/faucet-src/clib/mininet_test_base.py", line 1746, in retry_net_ping
    self.fail('ping %f loss > required loss %f' % (loss, required_loss))
AssertionError: ping 100.000000 loss > required loss 0.000000

----------------------------------------------------------------------
Ran 1 test in 149.013s

FAILED (failures=1)
```
Any prospect that we may use DP port numbers other than 1 to 4 for this test in the future?

**Comment by anarkiwi** [comment]
Are you reporting this as a problem when running the hardware test suite? If so this would be a bug in our test, which I will fix.
