### ISSUE TITLE
Unhandled exception when socket is already in use

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#2117]
Jun 27 02:52:36 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/faucet/faucet.py", line 126, in start
    self.metrics.start(prom_port, prom_addr)
  File "/usr/lib/python3/dist-packages/faucet/prom_client.py", line 87, in start
    self.server = hub.WSGIServer((prom_addr, int(prom_port)), app)
  File "/usr/lib/python3/dist-packages/ryu/lib/hub.py", line 126, in __init__
    self.server = eventlet.listen(listen_info)
  File "/usr/lib/python3/dist-packages/eventlet/convenience.py", line 43, in listen
    sock.bind(addr)
OSError: [Errno 98] Address already in use

**Comment by anarkiwi** [comment]
This is a misconfiguration (we can't reconfigure from it).
