### ISSUE TITLE
Unhandled exception with keyboard interrupts when parsing config

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#2128]
Jul 02 02:40:30 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/faucet/faucet.py", line 155, in reload_config
    time.time(), self.config_file, delete_dp=self._delete_deconfigured_dp)
  File "/usr/lib/python3/dist-packages/faucet/valves_manager.py", line 138, in request_reload_configs
    self.load_configs(now, new_config_file, delete_dp=delete_dp)
  File "/usr/lib/python3/dist-packages/faucet/valves_manager.py", line 107, in load_configs
    new_dps = self.parse_configs(new_config_file)
  File "/usr/lib/python3/dist-packages/faucet/valves_manager.py", line 87, in parse_configs
    new_config_hashes, new_dps = dp_parser(new_config_file, self.logname)
  File "/usr/lib/python3/dist-packages/faucet/config_parser.py", line 51, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/usr/lib/python3/dist-packages/faucet/config_parser.py", line 199, in _config_parser_v2
    top_confs['vlans'])
  File "/usr/lib/python3/dist-packages/faucet/config_parser.py", line 165, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3/dist-packages/faucet/dp.py", line 707, in finalize_config
    resolve_acls()
  File "/usr/lib/python3/dist-packages/faucet/dp.py", line 670, in resolve_acls
    resolve_acl(acl)
  File "/usr/lib/python3/dist-packages/faucet/dp.py", line 645, in resolve_acl
    build_acl(acl, vid=1)
  File "/usr/lib/python3/dist-packages/faucet/dp.py", line 624, in build_acl
    ofmsg.serialize()
  File "/usr/lib/python3/dist-packages/ryu/ofproto/ofproto_parser.py", line 270, in serialize
    self._serialize_body()
  File "/usr/lib/python3/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 2743, in _serialize_body
    match_len = self.match.serialize(self.buf, offset)
  File "/usr/lib/python3/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 1049, in serialize
    if self._composed_with_old_api():
  File "/usr/lib/python3/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 1040, in _composed_with_old_api
    self._wc.__dict__ != FlowWildcards().__dict__
KeyboardInterrupt

**Comment by anarkiwi** [comment]
KeyboardInterrupt is fatal - operator wants us to stop and stop now, so there's not much to be done about it.
