### ISSUE TITLE
Bad LLDP message can crash faucet controller

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2165]
A bad LLDP message on a stack port can crash a faucet controller:

```
Jul 16 13:11:28 faucet.valve INFO     DPID 260367057409193 (0xeccd6df7d4a9) at-x930-1 FAUCET LLDP from Port 20 (remote DPID 260367057659067 (0xeccd6dfba4bb), port 23)
Jul 16 13:11:28 faucet.valve INFO     DPID 260367057409193 (0xeccd6df7d4a9) at-x930-1 Stack Port 20 UP
Jul 16 13:11:28 faucet.valve INFO     DPID 260367057409193 (0xeccd6df7d4a9) at-x930-1 FAUCET LLDP from Port 21 (remote DPID 260367057659088 (0xeccd6dfba4d0), port 23)
Jul 16 13:11:28 faucet.valve INFO     DPID 260367057409193 (0xeccd6df7d4a9) at-x930-1 Stack Port 21 UP
Jul 16 13:11:28 faucet.valve INFO     DPID 260367057409193 (0xeccd6df7d4a9) at-x930-1 FAUCET LLDP from Port 19 (remote DPID 260367057659067 (0xeccd6dfba4bb), port 22)
Jul 16 13:11:28 faucet.valve INFO     DPID 260367057409193 (0xeccd6df7d4a9) at-x930-1 Stack Port 19 UP
Jul 16 13:11:28 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/faucet/faucet.py", line 233, in packet_in_handler
    self.valves_manager.valve_packet_in(ryu_event.timestamp, valve, msg)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valves_manager.py", line 171, in valve_packet_in
    ofmsgs = valve.rcv_packet(now, self._other_running_valves(valve), pkt_meta)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 1221, in rcv_packet
    self.lldp_handler(now, pkt_meta)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 947, in lldp_handler
    remote_port_id, remote_port_state) = self._parse_faucet_lldp(lldp_pkt)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 925, in _parse_faucet_lldp
    remote_port_state = int(port_state_tlvs[0].info)
IndexError: list index out of range

```

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/pull/2232.
