### ISSUE TITLE
Faucet will crash on impossible stack topology

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2166]
```
Jul 16 13:07:53 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/faucet/faucet.py", line 155, in reload_config
    time.time(), self.config_file, delete_dp=self._delete_deconfigured_dp)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valves_manager.py", line 138, in request_reload_configs
    self.load_configs(now, new_config_file, delete_dp=delete_dp)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valves_manager.py", line 122, in load_configs
    valve = self.new_valve(new_dp)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valves_manager.py", line 97, in new_valve
    return valve_cl(new_dp, self.logname, self.metrics, self.notifier)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 95, in __init__
    self.dp_init()
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve.py", line 163, in dp_init
    self.dp.shortest_path_to_root, self.dp.shortest_path_port)
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_flood.py", line 240, in __init__
    self._reset_peer_distances()
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_flood.py", line 245, in _reset_peer_distances
    (port, len(port.stack['dp'].shortest_path_to_root())) for port in self.stack_ports]
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_flood.py", line 245, in <listcomp>
    (port, len(port.stack['dp'].shortest_path_to_root())) for port in self.stack_ports]
  File "/usr/local/lib/python3.5/dist-packages/faucet/dp.py", line 432, in shortest_path_to_root
    return self.shortest_path(root_dp.name)
  File "/usr/local/lib/python3.5/dist-packages/faucet/dp.py", line 423, in shortest_path
    self.stack['graph'], self.name, dest_dp)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 142, in shortest_path
    paths = nx.bidirectional_shortest_path(G, source, target)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 226, in bidirectional_shortest_path
    results = _bidirectional_pred_succ(G, source, target)
  File "/usr/local/lib/python3.5/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 294, in _bidirectional_pred_succ
    raise nx.NetworkXNoPath("No path between %s and %s." % (source, target))
networkx.exception.NetworkXNoPath: No path between aruba-2930f-1 and at-x930-1.
```

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/pull/2231.
