### ISSUE TITLE
ModuleNotFoundError: No module named 'pytricia' - when running check_faucet_config /etc/faucet/faucet.yaml

### ISSUE THREAD

**Issue by Dru90** [faucetsdn/faucet#2322]
:~$ check_faucet_config /etc/faucet/faucet.yaml
Traceback (most recent call last):
  File "/usr/bin/check_faucet_config", line 6, in <module>
    from faucet.check_faucet_config import main
  File "/usr/lib/python3/dist-packages/faucet/check_faucet_config.py", line 26, in <module>
    from faucet.config_parser import dp_parser
  File "/usr/lib/python3/dist-packages/faucet/config_parser.py", line 28, in <module>
    from faucet.router import Router
  File "/usr/lib/python3/dist-packages/faucet/router.py", line 19, in <module>
    import pytricia
ModuleNotFoundError: No module named 'pytricia'

After a fresh install (following documentation 'Installing faucet for the first time') on Ubuntu Desktop 18.04 the module named pytricia is not found. 

Can anyone help?

**Comment by gizmoguy** [comment]
You are quite right, we broke our apt packages (which is what the tutorial uses).

We will be releasing faucet 1.8.16 in the next hour which will fix the issue (please just run apt-get update && apt-get upgrade to get the fixed version).

I have also added a test to our test suite to ensure we have all dependancies packaged so this doesn't happen in the future.

Sorry about the confusion!

**Comment by Dru90** [comment]
thanks!
