### ISSUE TITLE
dump_failed_test_file tried to open a pcap file with UTF-8

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#2327]
This is new with the change of the default encoding to utf-8. dump_failed_test_file reads the contents of each file before checking the extension. This fails with binary pcap files.

```
Traceback (most recent call last):
  File "./mininet_main.py", line 18, in <module>
    test_main(mininet_tests.__name__)
  File "/faucet-src/clib/clib_mininet_test_main.py", line 677, in test_main
    keep_logs, serial, excluded_test_classes, report_json_filename)
  File "/faucet-src/clib/clib_mininet_test_main.py", line 609, in run_tests
    sanity_result.wasSuccessful(), keep_logs, dumpfail)
  File "/faucet-src/clib/clib_mininet_test_main.py", line 573, in clean_test_dirs
    dump_failed_test(test_name, test_dir)
  File "/faucet-src/clib/clib_mininet_test_main.py", line 557, in dump_failed_test
    if dump_failed_test_file(test_file, only_exts):
  File "/faucet-src/clib/clib_mininet_test_main.py", line 528, in dump_failed_test_file
    test_file_content = open(test_file).read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 0: invalid continuation byte
```

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/commit/aa66a429823063b6492db5cd63b2bd305dd4b2bf
