### ISSUE TITLE
Possible ICMPv6 handler error

### ISSUE THREAD

**Issue by lantz** [faucetsdn/faucet#2330]
I ran into this exception in my testing - perhaps it is possible for a bad ICMPv6 packet to cause this exception? Or maybe something isn't being parsed properly because it is `bytes` rather than an `str`.

```
======================================================================
FAIL: test_fuzz_controller (mininet_tests.FaucetUntaggedIPv6ControlPlaneFuzzTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/clib/mininet_test_base.py", line 303, in tearDown
    self.verify_no_exception(self.env['faucet']['FAUCET_EXCEPTION_LOG'])
  File "/faucet-src/clib/mininet_test_base.py", line 571, in verify_no_exception
    exception_log_name, exception_contents))
AssertionError: '' != 'Aug 23 05:31:12 faucet.exception ERROR   [1143 chars]\'\n'
Diff is 1204 characters long. Set self.maxDiff to None to see it. : /var/tmp/faucet-tests-m11hwvfo/FaucetUntaggedIPv6ControlPlaneFuzzTest-test_fuzz_controller/faucet-exception.log log contains Aug 23 05:31:12 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/faucet-src/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/faucet-src/faucet/faucet.py", line 233, in packet_in_handler
    self.valves_manager.valve_packet_in(ryu_event.timestamp, valve, msg)
  File "/faucet-src/faucet/valves_manager.py", line 173, in valve_packet_in
    ofmsgs = valve.rcv_packet(now, self._other_running_valves(valve), pkt_meta)
  File "/faucet-src/faucet/valve.py", line 1257, in rcv_packet
    now, pkt_meta, route_manager)
  File "/faucet-src/faucet/valve.py", line 1011, in _control_plane_handler
    return route_manager.control_plane_handler(now, pkt_meta)
  File "/faucet-src/faucet/valve_route.py", line 925, in control_plane_handler
    now, pkt_meta, ipv6_pkt)
  File "/faucet-src/faucet/valve_route.py", line 917, in _control_plane_icmpv6_handler
    self, now, pkt_meta, ipv6_pkt, icmpv6_pkt, src_ip, dst_ip)
  File "/faucet-src/faucet/valve_route.py", line 881, in _echo_request_handler
    icmpv6_pkt.data.id, icmpv6_pkt.data.seq,
AttributeError: 'bytes' object has no attribute 'id'


----------------------------------------------------------------------
Ran 3 tests in 265.155s

FAILED (failures=2)
```

**Comment by anarkiwi** [comment]
Aha, looks like scapy has found a way to create a ICMPv6 packet with type echo, but an invalid payload. 
I'll handle this.

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/commit/054871dc19fa5c21086fe9be93a60b4b15c718cd
