### ISSUE TITLE
Unit Test Case FaucetSanityTest would not pass for certain dp port numbers

### ISSUE THREAD

**Issue by ethanyen1112** [faucetsdn/faucet#2654]
If using any DP port numbers other than 1 to 4, **FaucetSanityTest** would not pass since version 1.8.27.

For example, if DP port numbers are from 1 to 4, this test case would pass.
```
verifying cabling for port_1: host enp1s0f0 -> dp 1
DP 1 is port1.0.1, at 1000 mbps
verifying cabling for port_2: host enp1s0f1 -> dp 2
DP 2 is port1.0.2, at 1000 mbps
verifying cabling for port_3: host enp1s0f2 -> dp 3
DP 3 is port1.0.3, at 1000 mbps
verifying cabling for port_4: host enp1s0f3 -> dp 4
DP 4 is port1.0.4, at 1000 mbps
ok
test_untagged (mininet_tests.FaucetSanityTest)
All hosts on the same untagged VLAN should have connectivity. ... ok

----------------------------------------------------------------------
Ran 3 tests in 147.643s

OK
```
However, if DP port numbers are from 11 to 14 (or any port other than 1 to 4), this test would fail as below:
```
verifying cabling for port_1: host enp1s0f0 -> dp 11
DP 11 is port1.0.11, at 1000 mbps
verifying cabling for port_2: host enp1s0f1 -> dp 12
DP 12 is port1.0.12, at 1000 mbps
verifying cabling for port_3: host enp1s0f2 -> dp 13
DP 13 is port1.0.13, at 1000 mbps
verifying cabling for port_4: host enp1s0f3 -> dp 14
DP 14 is port1.0.14, at 1000 mbps
ok
test_untagged (mininet_tests.FaucetSanityTest)
All hosts on the same untagged VLAN should have connectivity. ... FAIL

======================================================================
FAIL: test_untagged (mininet_tests.FaucetSanityTest)
All hosts on the same untagged VLAN should have connectivity.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 148, in test_untagged
    self.flap_all_switch_ports()
  File "/faucet-src/clib/mininet_test_base.py", line 1795, in flap_all_switch_ports
    self.flap_port(port_no, flap_time=flap_time)
  File "/faucet-src/clib/mininet_test_base.py", line 1788, in flap_port
    self.set_port_down(port_no)
  File "/faucet-src/clib/mininet_test_base.py", line 1748, in set_port_down
    self.set_port_status(dpid, port_no, OFPPC_PORT_DOWN, wait)
  File "/faucet-src/clib/mininet_test_base.py", line 1745, in set_port_status
    self.wait_port_status(int(dpid), port_no, status, expected_status)
  File "/faucet-src/clib/mininet_test_base.py", line 1735, in wait_port_status
    dpid, port_no, port_status, expected_status))
AssertionError: dpid 112233445566 port 11 status None != expected 0

----------------------------------------------------------------------
Ran 3 tests in 188.500s

FAILED (failures=1)
```
For reference, I traced down the code and it seems to be related to the commit "Add port_description to port variables." [https://github.com/faucetsdn/faucet/commit/fad61e38fb3a53dd15e69090c92dbcdc91913aec](url)
After I reverted this commit, this test case would pass using port number 11 to 14.

**Comment by gizmoguy** [comment]
Sorry about that, we'll have a new version (1.8.28) released tomorrow that includes the fix, thanks for your bug report!
