### ISSUE TITLE
faucet 1.8.29 apt packages are bad

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2689]
```
root@3b6361076b99:/# faucet
loading app faucet.faucet
Traceback (most recent call last):
  File "/usr/bin/ryu-manager", line 11, in <module>
    load_entry_point('ryu==4.30', 'console_scripts', 'ryu-manager')()
  File "/usr/lib/python3/dist-packages/ryu/cmd/manager.py", line 98, in main
    app_mgr.load_apps(app_lists)
  File "/usr/lib/python3/dist-packages/ryu/base/app_manager.py", line 415, in load_apps
    cls = self.load_app(app_cls_name)
  File "/usr/lib/python3/dist-packages/ryu/base/app_manager.py", line 392, in load_app
    mod = utils.import_module(name)
  File "/usr/lib/python3/dist-packages/ryu/utils.py", line 108, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/faucet/faucet.py", line 39, in <module>
    from faucet import faucet_dot1x
  File "/usr/lib/python3/dist-packages/faucet/faucet_dot1x.py", line 25, in <module>
    from chewie import chewie  # pylint: disable=wrong-import-position
  File "/usr/lib/python3/dist-packages/chewie/chewie.py", line 10, in <module>
    from chewie.eap_state_machine import FullEAPStateMachine
  File "/usr/lib/python3/dist-packages/chewie/eap_state_machine.py", line 4, in <module>
    from transitions import Machine, State
ModuleNotFoundError: No module named 'transitions'
```

**Comment by gizmoguy** [comment]
faucet 1.8.30 fixes this
