### ISSUE TITLE
Verify how exceptions are logged

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2846]
Faucet logs normal messages to faucet.log and exceptions to faucet_exception.log.

We should verify that exceptions end up in both files.

**Comment by anarkiwi** [comment]
They do.

root@faucet:~# tail /var/tmp/faucet-tests-ti426t3k/Faucet8021XSuccessTest-test_untagged/faucet.log
Mar 25 06:22:32 faucet ERROR    unexpected chewie thread termination - check Ryu/process stderr log
Mar 25 06:22:32 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/faucet-src/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/faucet-src/faucet/faucet.py", line 123, in _check_thread_exception
    super(Faucet, self)._check_thread_exception()
  File "/faucet-src/faucet/valve_ryuapp.py", line 90, in _check_thread_exception
    raise ValveDeadThreadException
faucet.valve_ryuapp.ValveDeadThreadException
root@faucet:~# tail /var/tmp/faucet-tests-ti426t3k/Faucet8021XSuccessTest-test_untagged/faucet-exception.log 
Mar 25 06:22:32 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/faucet-src/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/faucet-src/faucet/faucet.py", line 123, in _check_thread_exception
    super(Faucet, self)._check_thread_exception()
  File "/faucet-src/faucet/valve_ryuapp.py", line 90, in _check_thread_exception
    raise ValveDeadThreadException
faucet.valve_ryuapp.ValveDeadThreadException
