### ISSUE TITLE
hw testing broken in 1.9.5

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#2977]
======================================================================
ERROR: test_untagged (mininet_tests.FaucetUntaggedTest)
All hosts on the same untagged VLAN should have connectivity.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 133, in setUp
    self.port_map = self.create_port_map(self.dpid)
  File "/faucet-src/clib/mininet_test_base.py", line 472, in create_port_map
    ports = self.topo.dpid_ports(dpid)
  File "/faucet-src/clib/mininet_test_topo.py", line 200, in dpid_ports
    switch = self._dpid_names[dpid]
KeyError: '1296'

**Comment by anarkiwi** [comment]
Fixed in 1.9.6 and tests added https://github.com/faucetsdn/faucet/commit/2fcd28245418c3adb3ddc9393c90aae8bf8c3a6d
