### ISSUE TITLE
Local integration tests fail on FaucetDockerHostTest

### ISSUE THREAD

**Issue by lantz** [faucetsdn/faucet#3185]
I have been running the integration tests locally following the instructions at https://docs.faucet.nz/en/latest/testing.html#running-the-tests:

```
sudo docker build --pull -t faucet/tests -f Dockerfile.tests .
sudo docker run --privileged --rm --net=host --cap-add=NET_ADMIN \
                -v /var/local/lib/docker:/var/lib/docker \
                -v /tmp/faucet-pip-cache:/var/tmp/pip-cache \
                -v /etc/faucet:/etc/faucet \
                -v /var/tmp:/var/tmp \
                -ti faucet/tests
```

I noticed `FaucetDockerHostTest` failing because it cannot connect to the docker daemon:

```
running 0 tests in parallel and 2 tests serial
test_containers (clib_mininet_tests.FaucetDockerHostTest)
Test containers to make sure they're actually docker. ... e011: docker image faucet/test-host not available locally - pulling
docker pull failed with error 1 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 
docker cmd: docker run -ti --privileged --entrypoint env -h e011 --name mininet-e011 --net=none --env TERM=dumb --env PS1= -v /var/tmp/faucet-tests-9s7xfm4s/FaucetDockerHostTest-test_containers/e011/tmp:/tmp faucet/test-host bash --norc -is mininet:e011FAIL
test_ping_all (clib_mininet_tests.FaucetDockerHostTest)
All hosts should have connectivity. ... e021: docker image faucet/test-host not available locally - pulling
docker pull failed with error 1 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 
docker cmd: docker run -ti --privileged --entrypoint env -h e021 --name mininet-e021 --net=none --env TERM=dumb --env PS1= -v /var/tmp/faucet-tests-9s7xfm4s/FaucetDockerHostTest-test_ping_all/e021/tmp:/tmp faucet/test-host bash --norc -is mininet:e021FAIL

======================================================================
FAIL: test_containers (clib_mininet_tests.FaucetDockerHostTest)
Test containers to make sure they're actually docker.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/clib/clib_mininet_tests.py", line 52, in setUp
    self.start_net()
  File "/faucet-src/clib/mininet_test_base.py", line 463, in start_net
    self._start_faucet(controller_intf, controller_ipv6)
  File "/faucet-src/clib/mininet_test_base.py", line 525, in _start_faucet
    test_name=self._test_name()))
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/net.py", line 174, in __init__
    self.build()
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/net.py", line 502, in build
    self.buildFromTopo( self.topo )
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/net.py", line 473, in buildFromTopo
    self.addHost( hostName, **topo.nodeInfo( hostName ) )
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/net.py", line 226, in addHost
    h = cls( name, **defaults )
  File "/faucet-src/clib/docker_host.py", line 315, in __init__
    super(_ImageHost, self).__init__(*args, **kwargs)
  File "/faucet-src/clib/docker_host.py", line 70, in __init__
    Host.__init__(self, name, **kwargs)
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/node.py", line 111, in __init__
    self.startShell()
  File "/faucet-src/clib/docker_host.py", line 126, in startShell
    data = self.read(maxbytes=1)
  File "/faucet-src/clib/docker_host.py", line 235, in read
    (self.stdout.fileno(), self.startup_timeout_ms / 1e3))
AssertionError: Timeout waiting for read data on 8 after 90s

======================================================================
FAIL: test_ping_all (clib_mininet_tests.FaucetDockerHostTest)
All hosts should have connectivity.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/clib/clib_mininet_tests.py", line 52, in setUp
    self.start_net()
  File "/faucet-src/clib/mininet_test_base.py", line 463, in start_net
    self._start_faucet(controller_intf, controller_ipv6)
  File "/faucet-src/clib/mininet_test_base.py", line 525, in _start_faucet
    test_name=self._test_name()))
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/net.py", line 174, in __init__
    self.build()
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/net.py", line 502, in build
    self.buildFromTopo( self.topo )
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/net.py", line 473, in buildFromTopo
    self.addHost( hostName, **topo.nodeInfo( hostName ) )
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/net.py", line 226, in addHost
    h = cls( name, **defaults )
  File "/faucet-src/clib/docker_host.py", line 315, in __init__
    super(_ImageHost, self).__init__(*args, **kwargs)
  File "/faucet-src/clib/docker_host.py", line 70, in __init__
    Host.__init__(self, name, **kwargs)
  File "/venv/lib/python3.6/site-packages/mininet-2.3.0d4-py3.6.egg/mininet/node.py", line 111, in __init__
    self.startShell()
  File "/faucet-src/clib/docker_host.py", line 126, in startShell
    data = self.read(maxbytes=1)
  File "/faucet-src/clib/docker_host.py", line 235, in read
    (self.stdout.fileno(), self.startup_timeout_ms / 1e3))
AssertionError: Timeout waiting for read data on 12 after 90s

----------------------------------------------------------------------
Ran 2 tests in 191.511s

FAILED (failures=2)

```

This may be an instance of nested docker not working - I'm not sure whether this is new behavior though.

This can also be reproduced by running `FaucetDockerHostTest` individually:

```sudo docker run --privileged --rm --net=host --cap-add=NET_ADMIN                 -v /var/local/lib/docker:/var/lib/docker                 -v /tmp/faucet-pip-cache:/var/tmp/pip-cache                 -v /var/tmp:/var/tmp                 -v $PWD:/faucet-src                 -e FAUCET_TESTS='-ink FaucetDockerHostTest'                 -ti faucet/tests ```

**Comment by gizmoguy** [comment]
Hi @lantz 

These tests use docker-in-docker which can sometimes be problematic on some systems. Could you please let me know your kernel and docker-ce version and I'll try to reproduce your problem.

**Comment by lantz** [comment]
Hmm, I'm not sure what docker-ce is, but  I'm using Linux 4.18.0 and docker 18.09.7.

**Comment by anarkiwi** [comment]
FWIW, I'm using and I don't see this problem.

root@faucet:~# uname -a
Linux faucet 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@faucet:~# grep -r docker /etc/apt/
/etc/apt/sources.list:deb [arch=amd64] http://download.docker.com/linux/ubuntu bionic stable # disabled on upgrade to bionic
/etc/apt/sources.list:# deb-src [arch=amd64] http://download.docker.com/linux/ubuntu xenial stable
/etc/apt/sources.list:# deb-src [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
/etc/apt/sources.list:# deb-src [arch=amd64] http://download.docker.com/linux/ubuntu bionic stable
Binary file /etc/apt/trusted.gpg~ matches
Binary file /etc/apt/trusted.gpg matches
root@faucet:~# docker --version
Docker version 19.03.2, build 6a30dfc
root@faucet:~# lsb_release -d
Description:	Ubuntu 18.04.3 LTS

**Comment by anarkiwi** [comment]
Should we investigate this further?

**Comment by anarkiwi** [comment]
Please reopen if still a problem.
