### ISSUE TITLE
Possible port order dependency in FaucetSingleStackStringOf3DPExtLoopProtUntaggedTest

### ISSUE THREAD

**Issue by lantz** [faucetsdn/faucet#3191]
I've noticed it running slowly and failing both locally and on travis (such as https://travis-ci.com/faucetsdn/faucet/jobs/226499219 for PR #3184).

For example, I just ran this (FAUCET version 1.9.15 2ca0926):

```
for order in 0,1,2,3 3,0,2,1; do sudo docker run --privileged --rm --net=host --cap-add=NET_ADMIN                 -v /var/local/lib/docker:/var/lib/docker                 -v /tmp/faucet-pip-cache:/var/tmp/pip-cache                 -v /var/tmp:/var/tmp                 -v $PWD:/faucet-src                 -e FAUCET_TESTS="-ink -o $order FaucetSingleStackStringOf3DPExtLoopProtUntaggedTest"                 -ti faucet/tests; done
Using pip cache
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/test-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/fuzz-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/docs/requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/adapters/vendors/rabbitmq/requirements.txt has exit status 0
========== checking IPv4/v6 localhost is up =====
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.036 ms

--- ::1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.036/0.036/0.036/0.000 ms
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.028 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.028/0.028/0.028/0.000 ms
========== Starting OVS =========================
 * /usr/local/etc/openvswitch/conf.db does not exist
 * Creating empty database /usr/local/etc/openvswitch/conf.db
 * Starting ovsdb-server
 * system ID not configured, please use --system-id
 * Configuring Open vSwitch system IDs
 * Starting ovs-vswitchd
 * Enabling remote OVSDB managers
8fdee16d-424f-4604-bb22-95f1c02fb436
    ovs_version: "2.11.0"
net.ipv4.neigh.default.gc_interval = 300
net.ipv4.neigh.default.gc_thresh1 = 8192
net.ipv4.neigh.default.gc_thresh2 = 16384
net.ipv4.neigh.default.gc_thresh3 = 32768
net.ipv6.neigh.default.gc_interval = 300
net.ipv6.neigh.default.gc_thresh1 = 8192
net.ipv6.neigh.default.gc_thresh2 = 16384
net.ipv6.neigh.default.gc_thresh3 = 32768
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
========== Starting docker container ==========
 * Starting Docker: docker                                                                          [ OK ] 
========== Running faucet system tests ==========
testing module mininet_tests
Cleaning up test interfaces, processes and openvswitch configuration from previous test runs
testing module mininet_tests
Skipping dependency checks
port order: -o 0,1,2,3
Using config from /faucet-src/hw_switch_config.yaml
Logging test results in /var/tmp/faucet-tests-8wwnld4r
test ports server started
adding test FaucetSingleStackStringOf3DPExtLoopProtUntaggedTest

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running 0 tests in parallel and 1 tests serial
test_untagged (mininet_tests.FaucetSingleStackStringOf3DPExtLoopProtUntaggedTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 439.479s

OK


test results
============
--- {}
...

table: 0
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_DST/Mask', 'OFPXMT_OFB_ETH_TYPE', 'OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 2)
  table_actions: ['OFPAT_OUTPUT', 'OFPAT_PUSH_VLAN', 'OFPAT_SET_FIELD'] (max 3)
table: 1
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_DST/Mask', 'OFPXMT_OFB_ETH_SRC', 'OFPXMT_OFB_ETH_TYPE', 'OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 2)
  table_actions: ['OFPAT_OUTPUT'] (max 1)
table: 2
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_VLAN_PCP', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 1)
  table_actions: ['OFPAT_OUTPUT', 'OFPAT_POP_VLAN'] (max 2)
table: 3
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_DST/Mask', 'OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_PCP', 'OFPXMT_OFB_VLAN_VID'] (max 4)
  table_instructions: ['OFPIT_APPLY_ACTIONS'] (max 1)
  table_actions: ['OFPAT_OUTPUT', 'OFPAT_POP_VLAN', 'OFPAT_SET_FIELD'] (max 6)

real	7m22.742s
user	0m58.754s
sys	0m13.823s
testing module clib_mininet_tests
Skipping dependency checks
port order: -o 0,1,2,3
Using config from /faucet-src/hw_switch_config.yaml
Logging test results in /var/tmp/faucet-tests-0rwusw5y
test ports server started
no tests selected

real	0m1.515s
user	0m0.452s
sys	0m0.050s
Done with faucet system tests.
Using pip cache
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/test-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/fuzz-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/docs/requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/adapters/vendors/rabbitmq/requirements.txt has exit status 0
========== checking IPv4/v6 localhost is up =====
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.030 ms

--- ::1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.030/0.030/0.030/0.000 ms
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.035 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.035/0.035/0.035/0.000 ms
========== Starting OVS =========================
 * /usr/local/etc/openvswitch/conf.db does not exist
 * Creating empty database /usr/local/etc/openvswitch/conf.db
 * Starting ovsdb-server
 * system ID not configured, please use --system-id
 * Configuring Open vSwitch system IDs
 * Starting ovs-vswitchd
 * Enabling remote OVSDB managers
0b88e8a1-f95a-4d2b-9b30-79dd7eb77e33
    ovs_version: "2.11.0"
net.ipv4.neigh.default.gc_interval = 300
net.ipv4.neigh.default.gc_thresh1 = 8192
net.ipv4.neigh.default.gc_thresh2 = 16384
net.ipv4.neigh.default.gc_thresh3 = 32768
net.ipv6.neigh.default.gc_interval = 300
net.ipv6.neigh.default.gc_thresh1 = 8192
net.ipv6.neigh.default.gc_thresh2 = 16384
net.ipv6.neigh.default.gc_thresh3 = 32768
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
========== Starting docker container ==========
 * Starting Docker: docker                                                                          [ OK ] 
========== Running faucet system tests ==========
testing module mininet_tests
Cleaning up test interfaces, processes and openvswitch configuration from previous test runs
testing module mininet_tests
Skipping dependency checks
port order: -o 3,0,2,1
Using config from /faucet-src/hw_switch_config.yaml
Logging test results in /var/tmp/faucet-tests-w67seb_m
test ports server started
adding test FaucetSingleStackStringOf3DPExtLoopProtUntaggedTest

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running 0 tests in parallel and 1 tests serial
test_untagged (mininet_tests.FaucetSingleStackStringOf3DPExtLoopProtUntaggedTest) ... FAIL

======================================================================
FAIL: test_untagged (mininet_tests.FaucetSingleStackStringOf3DPExtLoopProtUntaggedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 7345, in test_untagged
    self.verify_unicast(hosts=(int_host, other_int_host), unicast_expected=True)
  File "/faucet-src/clib/mininet_test_base.py", line 1487, in verify_unicast
    self._verify_xcast(unicast_expected, packets, tcpdump_filter, scapy_cmd, host_a, host_b)
  File "/faucet-src/clib/mininet_test_base.py", line 1459, in _verify_xcast
    received_expected, received_packets, msg=msg)
AssertionError: True != False : u023 (96:aa:9a:87:e8:6e) -> u033 (a2:76:d4:83:38:26): 0 packets captured0 packets received by filter0 packets dropped by kernel

----------------------------------------------------------------------
Ran 1 test in 54.995s

FAILED (failures=1)


test results
============
---
mininet_tests.FaucetSingleStackStringOf3DPExtLoopProtUntaggedTest.test_untagged:
  output: "Traceback (most recent call last):\t  File '/faucet-src/tests/integration/mininet_tests.py',\
    \ line 7345, in test_untagged\t    self.verify_unicast(hosts=(int_host, other_int_host),\
    \ unicast_expected=True)\t  File '/faucet-src/clib/mininet_test_base.py', line\
    \ 1487, in verify_unicast\t    self._verify_xcast(unicast_expected, packets, tcpdump_filter,\
    \ scapy_cmd, host_a, host_b)\t  File '/faucet-src/clib/mininet_test_base.py',\
    \ line 1459, in _verify_xcast\t    received_expected, received_packets, msg=msg)\t\
    AssertionError: True != False : u023 (96:aa:9a:87:e8:6e) -> u033 (a2:76:d4:83:38:26):\
    \ 0 packets captured0 packets received by filter0 packets dropped by kernel\t"
  status: FAIL
  test_duration_secs: 54
...

table: 0
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_DST/Mask', 'OFPXMT_OFB_ETH_TYPE', 'OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 2)
  table_actions: ['OFPAT_OUTPUT', 'OFPAT_PUSH_VLAN', 'OFPAT_SET_FIELD'] (max 3)
table: 1
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_DST/Mask', 'OFPXMT_OFB_ETH_SRC', 'OFPXMT_OFB_ETH_TYPE', 'OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 2)
  table_actions: ['OFPAT_OUTPUT'] (max 1)
table: 2
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_VLAN_PCP', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 1)
  table_actions: ['OFPAT_OUTPUT', 'OFPAT_POP_VLAN'] (max 2)
table: 3
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_DST/Mask', 'OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_PCP', 'OFPXMT_OFB_VLAN_VID'] (max 4)
  table_instructions: ['OFPIT_APPLY_ACTIONS'] (max 1)
  table_actions: ['OFPAT_OUTPUT', 'OFPAT_POP_VLAN', 'OFPAT_SET_FIELD'] (max 6)

log/debug files for failed tests are in /var/tmp/faucet-tests-w67seb_m


real	0m57.201s
user	0m10.534s
sys	0m6.963s
testing module clib_mininet_tests
Skipping dependency checks
port order: -o 3,0,2,1
Using config from /faucet-src/hw_switch_config.yaml
Logging test results in /var/tmp/faucet-tests-j1g66mss
test ports server started
no tests selected

real	0m1.540s
user	0m0.465s
sys	0m0.064s
Test failures: mininet_main
```

**Comment by lantz** [comment]
Great! I will test it locally.
