### ISSUE TITLE
Unknown ACL crashes RYU and subsequently can't set config back to last known good, as there isn't a last known good

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#3291]
```
Oct 16 00:20:00 faucet ERROR    New config bad (missing ACL protect-me in DP: x230) - rejecting
Oct 16 00:20:00 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/faucet/valves_manager.py", line 195, in parse_configs
    new_config_file, self.logname, self.meta_dp_state)
  File "/usr/lib/python3.7/site-packages/faucet/config_parser.py", line 54, in dp_parser
    config_file, logname, meta_dp_state)
  File "/usr/lib/python3.7/site-packages/faucet/config_parser.py", line 247, in _config_parser_v2
    dps = dp_preparsed_parser(top_confs, meta_dp_state)
  File "/usr/lib/python3.7/site-packages/faucet/config_parser.py", line 230, in dp_preparsed_parser
    meta_dp_state)
  File "/usr/lib/python3.7/site-packages/faucet/config_parser.py", line 199, in _dp_parser_v2
    dp.finalize_config(dps)
  File "/usr/lib/python3.7/site-packages/faucet/dp.py", line 1287, in finalize_config
    resolve_acls()
  File "/usr/lib/python3.7/site-packages/faucet/dp.py", line 1183, in resolve_acls
    resolve_acl(acl, port_num=port.number)
  File "/usr/lib/python3.7/site-packages/faucet/dp.py", line 1073, in resolve_acl
    'missing ACL %s in DP: %s' % (acl_in, self.name)))
  File "/usr/lib/python3.7/site-packages/faucet/conf.py", line 33, in test_config_condition
    raise InvalidConfigError(msg)
faucet.conf.InvalidConfigError: missing ACL protect-me in DP: x230

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/faucet/faucet.py", line 162, in reload_config
    time.time(), self.config_file, delete_dp=self._delete_deconfigured_dp)
  File "/usr/lib/python3.7/site-packages/faucet/valves_manager.py", line 277, in request_reload_configs
    result = self.load_configs(now, new_config_file, delete_dp=delete_dp)
  File "/usr/lib/python3.7/site-packages/faucet/valves_manager.py", line 262, in load_configs
    return self._apply_configs(self.parse_configs(new_config_file), now, delete_dp)
  File "/usr/lib/python3.7/site-packages/faucet/valves_manager.py", line 211, in parse_configs
    self.revert_config()
  File "/usr/lib/python3.7/site-packages/faucet/valves_manager.py", line 180, in revert_config
    for config_file_name, config_content in self.last_good_config.items():
AttributeError: 'ValvesManager' object has no attribute 'last_good_config'
```

**Comment by anarkiwi** [comment]
Also fixed by https://github.com/faucetsdn/faucet/pull/3299.
