### ISSUE TITLE
Cannot run 2 faucet controllers with dot1x

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#3576]
With Faucet, a Openflow switch can have multiple Faucet controllers for high availability (HA).  It is assumed that all these Faucet controllers have the same `faucet.yaml`.  Due to HA mode, we place the controllers in different domains.  Now, if we configure `dot1x` support for one controller domain with Faucet, the faucet controller in the other domain will not start with the below error.  This breaks the Faucet model for controllers.  

```
May 26 19:28:04 faucet.Chewie.EapSocket INFO     Setting up socket on interface: eno2
May 26 19:28:04 faucet.Chewie.EapSocket ERROR    Unable to setup socket: [Errno 19] No such device
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/chewie/chewie.py", line 94, in run
    self.setup_eap_socket()
  File "/usr/lib/python3.7/site-packages/chewie/chewie.py", line 275, in setup_eap_socket
    self.eap_socket.setup()
  File "/usr/lib/python3.7/site-packages/chewie/nfv_sockets.py", line 73, in setup
    self._setup(socket.htons(0x888e))
  File "/usr/lib/python3.7/site-packages/chewie/nfv_sockets.py", line 47, in _setup
    raise err
  File "/usr/lib/python3.7/site-packages/chewie/nfv_sockets.py", line 42, in _setup
    self.open(socket_filter)
  File "/usr/lib/python3.7/site-packages/chewie/nfv_sockets.py", line 52, in open
    self.socket.bind((self.interface_name, 0))
OSError: [Errno 19] No such device
```

**Comment by gizmoguy** [comment]
I don't think this is a problem we can easily solve.

Either use your automation to roll out configs with different interface names to different controllers, or rename the linux interface to be the same on all your controllers.

If you can come up with a feature we could implement to make this easier for you re-open a new ticket.
