### ISSUE TITLE
Crash updating labels, selecting a new root in a new stacked network (existing config but stack is new)

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#3636]
Jul 23 23:18:43 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/faucet/faucet.py", line 215, in _maintain_stack_root
    self.valves_manager.maintain_stack_root(time.time())
  File "/usr/lib/python3.7/site-packages/faucet/valves_manager.py", line 160, in maintain_stack_root
    labels = prev_root[0].base_prom_labels()
IndexError: list index out of range

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/pull/3635
