### ISSUE TITLE
self.stack_manager.chosen_towards_port might be None as stack is initializing with routing active

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#3694]
Sep 24 15:06:13 faucet.exception ERROR    Unhandled exception, killing RYU

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/faucet/valve_util.py", line 34, in __koe

    func(*args, **kwargs)

  File "/usr/local/lib/python3.7/dist-packages/faucet/faucet.py", line 232, in _valve_flow_services

    self._VALVE_SERVICES[type(ryu_event)][0])

  File "/usr/local/lib/python3.7/dist-packages/faucet/valves_manager.py", line 316, in valve_flow_services

    for service_valve, ofmsgs in valve_service_func(now, other_valves).items():

  File "/usr/local/lib/python3.7/dist-packages/faucet/valve.py", line 1448, in resolve_gateways

    ofmsgs.extend(route_manager.resolve_gateways(vlan, now))

  File "/usr/local/lib/python3.7/dist-packages/faucet/valve_route.py", line 598, in resolve_gateways

    unresolved_gateways, self.max_hosts_per_resolve_cycle)

  File "/usr/local/lib/python3.7/dist-packages/faucet/valve_route.py", line 572, in _resolve_gateways_flows

    resolve_flows = resolve_handler(ip_gw, entry, vlan, now)

  File "/usr/local/lib/python3.7/dist-packages/faucet/valve_route.py", line 522, in _resolve_gateway_flows

    resolve_flows = self._resolve_gw_on_vlan(vlan, faucet_vip, ip_gw)

  File "/usr/local/lib/python3.7/dist-packages/faucet/valve_route.py", line 204, in _resolve_gw_on_vlan

    vlan.faucet_mac, valve_of.mac.BROADCAST_STR, faucet_vip.ip, ip_gw)

  File "/usr/local/lib/python3.7/dist-packages/faucet/valve_route.py", line 188, in _flood_stack_links

    running_port_nos = [port.number for port in ports if port.running()]

  File "/usr/local/lib/python3.7/dist-packages/faucet/valve_route.py", line 188, in <listcomp>

    running_port_nos = [port.number for port in ports if port.running()]

AttributeError: 'NoneType' object has no attribute 'running'

**Comment by anarkiwi** [comment]
Fixed in https://github.com/faucetsdn/faucet/commit/6bbb24f593e8ecdf3206c0d16b6fbc57cc3b21ce
