### ISSUE TITLE
Intermittent failure of FaucetSingleStackStringOfDPTagged0Test

### ISSUE THREAD

**Issue by mwutzke** [faucetsdn/faucet#3908]
Seen with a single test cycle for #3907

```
======================================================================
ERROR: test_dp_root_hop_port (mininet_multidp_tests.FaucetSingleStackStringOfDPTagged0Test)
Test if dp_root_hop_port is set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/clib/mininet_test_base.py", line 484, in tearDown
    switch.cmd('%s del-br %s' % (self.VSCTL, switch.name))
  File "/faucet-src/clib/mininet_test_topo.py", line 188, in cmd
    raise RuntimeError(msg)
RuntimeError: ('ovs-vsctl del-br s1O',) exited with (1):'ovs-vsctl: no bridge named s1O
'

======================================================================
FAIL: test_dp_root_hop_port (mininet_multidp_tests.FaucetSingleStackStringOfDPTagged0Test)
Test if dp_root_hop_port is set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/faucet/faucet/tests/integration/mininet_multidp_tests.py", line 291, in test_dp_root_hop_port
    dpid=dp_id), sw2_root_port)
AssertionError: 7 != 8
```

Running the test external to GHA works (localtest.sh), as did re-trigging the GHA request.

**Comment by mwutzke** [comment]
This has only been seen once, and not in the last week. Will close this for now, and if this is seen again, it can be re-opened.
