### ISSUE TITLE
Intermittent integration failure: FaucetUntaggedMaxHostsTest

### ISSUE THREAD

**Issue by mwutzke** [faucetsdn/faucet#3925]
Executing FaucetUntaggedMaxHostsTest either locally, or under GHA, generally works.

Occasionally though, 1 of 2 failures is observed:
```
======================================================================
FAIL: test_untagged (mininet_tests.FaucetUntaggedMaxHostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 2719, in test_untagged
    self.assertEqual(2, len(learned_hosts))
AssertionError: 2 != 1
```
or
```
======================================================================
FAIL: test_untagged (mininet_tests.FaucetUntaggedMaxHostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 2724, in test_untagged
    'vlan_learn_bans', {'vlan': '100'}), 0)
AssertionError: 0 not greater than 0
```

**Comment by mwutzke** [comment]
Looking a the logs in the failures, it is apparent that the 2 Faucet instances are out of sync with each other. This results in the 2 Faucet instances making different / conflicting decisions about the state, and which flows to install.

The unsynchronised state occurs because:
- the start-up of the 2nd Faucet instance is delayed relative to the 1st instance (in some cases > 50sec)
- during this delay, the 1st instance learns network state, as the Mininet hosts perform IPv6 ND
