### ISSUE TITLE
CouchDB support in Gauge is not tested

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#448]
@shivarammysore  - CouchDB support in Gauge has no tests. In particular, it does not handle CouchDB being down (if CouchDB is down Gauge will crash).

CouchDB should get tests in the same way as InfluxDB is tested (ie the most basic down/up test).

instantiating app /home/faucet/faucet/src/ryu_faucet/org/onfsdn/faucet/gauge.py of Gauge
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 9, in <module>
    load_entry_point('ryu==4.11', 'console_scripts', 'ryu-manager')()
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 81, in main
    services.extend(app_mgr.instantiate_apps(**contexts))
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
    self._instantiate(app_name, cls, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 495, in _instantiate
    app = cls(*args, **kwargs)
  File "/home/faucet/faucet/src/ryu_faucet/org/onfsdn/faucet/gauge.py", line 77, in __init__
    watcher = watcher_factory(conf)(conf, self.logname)
  File "/home/faucet/faucet/src/ryu_faucet/org/onfsdn/faucet/watcher.py", line 455, in __init__
    self.setup()
  File "/home/faucet/faucet/src/ryu_faucet/org/onfsdn/faucet/watcher.py", line 106, in setup
    self.switch_database, exists = self.conn.create(self.conf.switches_doc)
  File "/home/faucet/faucet/src/ryu_faucet/org/onfsdn/faucet/nsodbc.py", line 91, in create
    self.database[db_name] = DatabaseCouch(self.conn.create(db_name))
  File "/usr/local/lib/python2.7/dist-packages/couchdb/client.py", line 207, in create
    self.resource.put_json(name)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 570, in put_json
    **params)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 585, in _request_json
    headers=headers, **params)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 581, in _request
    credentials=self.credentials)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 289, in request
    conn = self.connection_pool.get(url)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 507, in get
    conn.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/socket.py", line 69, in create_connection
    raise err
socket.error: [Errno 111] ECONNREFUSED

**Comment by shivarammysore** [comment]
I believe there is a setting in gauge.yaml which is "file" for flow_table
data.  Maybe we should use that as the default and comment out the CouchDB
part as documentation for folks who will use it.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/ba59208fc76382968d7d7c5dbcb0b9ce58765c72
